### ISSUE TITLE
Raise EOFError

### ISSUE THREAD

**Issue by HYL-Dave** [microsoft/OLive#106]
When I try Optimize_ONNX_Models_Latency_with_OLive.ipynb, the following occurs

2022-08-08 15:25:49,680 - olive.optimization_config - INFO - Checking the model file...
2022-08-08 15:25:49,695 - olive.optimization_config - INFO - Providers will be tested for optimization: ['CPUExecutionProvider', 'DnnlExecutionProvider']
2022-08-08 15:25:52,705 - olive.optimization_config - INFO - Checking the model file...
2022-08-08 15:25:52,720 - olive.optimization_config - INFO - Providers will be tested for optimization: ['CPUExecutionProvider', 'DnnlExecutionProvider']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hyl/Downloads/low_latency.py", line 24, in <module>
    result = optimize(opt_config)
  File "/home/hyl/.local/bin/.virtualenvs/Olive_cpu_py36/lib/python3.6/site-packages/olive/optimize.py", line 24, in optimize
    pretuning_inference_result = get_benchmark(optimization_config)
  File "/home/hyl/.local/bin/.virtualenvs/Olive_cpu_py36/lib/python3.6/site-packages/olive/optimization/tuning_process.py", line 202, in get_benchmark
    manager = Manager()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 513, in start
    self._process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "low_latency.py", line 24, in <module>
    result = optimize(opt_config)
  File "/home/hyl/.local/bin/.virtualenvs/Olive_cpu_py36/lib/python3.6/site-packages/olive/optimize.py", line 24, in optimize
    pretuning_inference_result = get_benchmark(optimization_config)
  File "/home/hyl/.local/bin/.virtualenvs/Olive_cpu_py36/lib/python3.6/site-packages/olive/optimization/tuning_process.py", line 202, in get_benchmark
    manager = Manager()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by leqiao-1** [comment]
Hi @HYL-Dave 
Thanks for reporting this issue. 
To run olive optimization in a python script, you can put this sample script in ```test.py``` and run directly with ```python test.py```
olive code needs to be inside a function due to some multiprocessing settings.
```
from olive.optimization_config import OptimizationConfig
from olive.optimize import optimize

def model_optimize():
    opt_config = OptimizationConfig(model_path = "inception_v2.onnx")
    result = optimize(opt_config)

if __name__ == "__main__":
    model_optimize()
````

**Comment by leqiao-1** [comment]
If you have any further concerns or questions, please reopen this issue.
