### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 7 validation errors for RunConfig

### ISSUE THREAD

**Issue by MrRace** [microsoft/Olive#1074]
**Describe the bug**
I followed the instructions in https://github.com/microsoft/Olive/tree/main/examples/whisper. 
Here's the translation of your text:

I first ran the following command to generate the configuration file:
```
python3 prepare_whisper_configs.py --model_name /share_model_zoo/LLM/openai/whisper-large-v3
```
Then I executed the following command, but encountered an error:
```
python3 -m olive.workflows.run --config whisper_cpu_int8.json --setup
```

I received the following error message:
```
pydantic.v1.error_wrappers.ValidationError: 7 validation errors for RunConfig
systems -> local_system -> config -> accelerators -> 0
  str type expected (type=type_error.str)
engine
  Invalid systems (type=value_error)
passes -> conversion
  Invalid engine (type=value_error)
passes -> transformers_optimization
  Invalid engine (type=value_error)
passes -> onnx_dynamic_quantization
  Invalid engine (type=value_error)
passes -> insert_beam_search
  Invalid engine (type=value_error)
passes -> prepost
  Invalid engine (type=value_error)
```

At that time, the **pydantic version was 2.6.4.** 
I tried installing pydantic below version 2.0: `pip3 install -U pydantic==1.10.15`. After installing pydantic, I ran the above command again, but still encountered an error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/share/opt/minicoda/lib/python3.11/site-packages/olive/workflows/run/__main__.py", line 23, in <module>
    run(**var_args)
  File "/share/opt/minicoda/lib/python3.11/site-packages/olive/workflows/run/run.py", line 235, in run
    config = RunConfig.parse_file(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 569, in pydantic.main.BaseModel.parse_file
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for RunConfig
systems -> local_system -> config -> accelerators -> 0
  str type expected (type=type_error.str)
engine
  Invalid systems (type=value_error)
passes -> conversion
  Invalid engine (type=value_error)
passes -> transformers_optimization
  Invalid engine (type=value_error)
passes -> onnx_dynamic_quantization
  Invalid engine (type=value_error)
passes -> insert_beam_search
  Invalid engine (type=value_error)
passes -> prepost
  Invalid engine (type=value_error)
```
Could you please advise on how to handle this issue? Thank you very much! My olive-ai version is 0.5.0

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Olive config**
```
{
    "input_model": {
        "type": "PyTorchModel",
        "config": {
            "model_script": "code/user_script.py",
            "script_dir": "code",
            "hf_config": {
                "model_class": "WhisperForConditionalGeneration",
                "model_name": "/share_model_zoo/LLM/openai/whisper-large-v3",
                "components": [
                    {
                        "name": "encoder_decoder_init",
                        "io_config": "get_encdec_io_config",
                        "component_func": "get_encoder_decoder_init",
                        "dummy_inputs_func": "encoder_decoder_init_dummy_inputs"
                    },
                    {
                        "name": "decoder",
                        "io_config": "get_dec_io_config",
                        "component_func": "get_decoder",
                        "dummy_inputs_func": "decoder_dummy_inputs"
                    }
                ],
                "from_pretrained_args": {
                    "attn_implementation": "eager"
                }
            }
        }
    },
    "systems": {
        "local_system": {
            "type": "LocalSystem",
            "config": {
                "accelerators": [
                    {
                        "device": "cpu",
                        "execution_providers": [
                            "CPUExecutionProvider"
                        ]
                    }
                ]
            }
        }
    },
    "evaluators": {
        "common_evaluator": {
            "metrics": [
                {
                    "name": "latency",
                    "type": "latency",
                    "sub_types": [
                        {
                            "name": "avg",
                            "priority": 1
                        }
                    ],
                    "user_config": {
                        "user_script": "code/user_script.py",
                        "script_dir": "code",
                        "data_dir": "data",
                        "dataloader_func": "whisper_dataloader",
                        "func_kwargs": {
                            "dataloader_func": {
                                "model_name": "/share_model_zoo/LLM/openai/whisper-large-v3",
                                "use_audio_decoder": true
                            }
                        }
                    }
                }
            ]
        }
    },
    "passes": {
        "conversion": {
            "type": "OnnxConversion",
            "config": {
                "target_opset": 17
            }
        },
        "transformers_optimization": {
            "type": "OrtTransformersOptimization",
            "config": {
                "optimization_options": {
                    "use_multi_head_attention": true
                },
                "use_gpu": false
            }
        },
        "onnx_dynamic_quantization": {
            "type": "OnnxDynamicQuantization",
            "config": {
                "per_channel": false,
                "reduce_range": false,
                "op_types_to_quantize": [
                    "MatMul",
                    "Gemm",
                    "Gather"
                ],
                "MatMulConstBOnly": false
            }
        },
        "insert_beam_search": {
            "type": "InsertBeamSearch",
            "config": {
                "use_forced_decoder_ids": false,
                "use_logits_processor": false,
                "fp16": false
            }
        },
        "prepost": {
            "type": "AppendPrePostProcessingOps",
            "config": {
                "tool_command": "whisper",
                "tool_command_args": {
                    "model_name": "/share_model_zoo/LLM/openai/whisper-large-v3",
                    "use_audio_decoder": true
                },
                "target_opset": 17
            }
        }
    },
    "engine": {
        "log_severity_level": 0,
        "host": "local_system",
        "target": "local_system",
        "evaluator": "common_evaluator",
        "evaluate_input_model": false,
        "clean_cache": false,
        "cache_dir": "cache",
        "output_dir": "models",
        "output_name": "whisper_cpu_int8"
    }
}
```

**Olive logs**
Add logs here.

**Other information**
 - OS: [e.g. Windows, Linux] 
 - Olive version: [e.g. 0.4.0 or main]  Olive version=0.5.0
 - ONNXRuntime package and version:  onnxruntime-gpu Version: 1.17.1

**Additional context**

**Comment by jambayk** [comment]
Hi, there was a recent change in Olive so the config you shared is not compatible with the version of Olive olive that you are using. 

We only keep our examples updated to the main branch so, if you would like to use the latest example, please install olive from source as described in https://microsoft.github.io/Olive/getstarted/installation.html#install-from-source. 

If for some reason you need to use a specific version of olive, say 0.5.0, please check out the corresponding tag for the repository:
```
git checkout tags/v0.2.0
```
