### ISSUE TITLE
Enabling openai/whisper-large-v3 using olive-ai-0.6.0 [onnxruntime-gpu: 1.17.1] on Intel  CPU/GPU is not supporting 

### ISSUE THREAD

**Issue by vijayaVTT** [microsoft/Olive#1134]
(whisper_dml) C:\Users\Local_Admin\Olive\examples\whisper>python test_transcription.py --config whisper_gpu_fp16.json
Traceback (most recent call last):
  File "test_transcription.py", line 128, in <module>
    output_text = main()
  File "test_transcription.py", line 94, in main
    olive_model = ONNXModelHandler(**output_model_json["config"])
KeyError: 'config'

![Screenshot 2024-05-02 175337](https://github.com/microsoft/Olive/assets/80213874/d3378112-b137-424d-b598-24c12587193e)

The steps were produced using link examples/whisper

Expecting simple inferenced output

did not change any config, implied default only.
Kindly help me fixing this issues.
Thanks in advance :)

**Comment by jambayk** [comment]
Can you share the logs from when you ran the workflow? Looks like the workflow failed and no model was generated.

**Comment by vijayaVTT** [comment]
> Can you share the logs from when you ran the workflow? Looks like the workflow failed and no model was generated.

[log.txt](https://github.com/microsoft/Olive/files/15196870/log.txt)
[Whisper DML Olive.md](https://github.com/microsoft/Olive/files/15196883/Whisper.DML.Olive.md)
