### ISSUE TITLE
error while inferencing the mistral LLM

### ISSUE THREAD

**Issue by himanshushukla12** [microsoft/Olive#1309]
Facing problem while doing the inferencing of mistral LLM example

````
Olive/examples/mistral$ python mistral.py --config mistral_fp16_optimize.json --inference --prompt "Language models are very useful"        
/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/examples/mistral/mistral.py", line 130, in <module>
    main()
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/examples/mistral/mistral.py", line 122, in main
    output = inference(args.model_id, optimized_model_dir, ep, args.prompt, args.max_length)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/examples/mistral/mistral.py", line 74, in inference
    tokenizer = AutoTokenizer.from_pretrained(model_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 814, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/home/z004x2xz/WorkAssignedByMatt/Olive/venv3.11/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3

```

**Other information**
 - OS: ubuntu 22.04
 - Olive version: 0.7.0
 - onnxruntime-genai: 0.3.0
 - onnxruntime-gpu: 1.18.1
 - Python 3.11.9

**Comment by samuel100** [comment]
You should update to the latest version of Olive, which now includes an easy-to-use CLI. Below are the steps to optimize a Mistral model and execute on the ONNX Runtime using the Generate API:

## 💾 Install Olive

We recommend installing in a separate conda or virtual environment using the following pip install:

```bash
pip install olive-ai[auto-opt]
pip install transformers==4.44.2
pip install onnxruntime-genai-cuda
```

## 🪄 Use the Auto Optimizer

Use the following command to automatically optimize a Mistral Model and quantize into int4 (you can change the precision to INT8, FP16 or FP32):

```bash
olive auto-opt \
    --model_name_or_path mistralai/Mistral-7B-v0.3 \
    --output_path models/Mistral-7B-v0.3 \
    --device gpu \
    --provider CUDAExecutionProvider \
    --use_model_builder \
    --use_ort_genai \
    --precision int4 \
    --log_level 1
```
</details>

## Inference on ORT

```python
# app.py
import onnxruntime_genai as og

model_folder = "models/Mistral-7B-v0.3/model"

# Load the base model and tokenizer
model = og.Model(model_folder)
tokenizer = og.Tokenizer(model)
tokenizer_stream = tokenizer.create_stream()

# Set the max length to something sensible by default,
# since otherwise it will be set to the entire context length
search_options = {}
search_options['max_length'] = 200
search_options['past_present_share_buffer'] = False

chat_template = "<|im_start|>user\n{input}<|im_end|>\n<|im_start|>assistant\n"

text = input("Input: ")

# Keep asking for input phrases
while text != "exit":
    if not text:
        print("Error, input cannot be empty")
        exit

    # generate prompt (prompt template + input)
    prompt = f'{chat_template.format(input=text)}'

    # encode the prompt using the tokenizer
    input_tokens = tokenizer.encode(prompt)

    params = og.GeneratorParams(model)
    params.set_search_options(**search_options)
    params.input_ids = input_tokens
    generator = og.Generator(model, params)

    print("Output: ", end='', flush=True)
    # stream the output
    try:
        while not generator.is_done():
            generator.compute_logits()
            generator.generate_next_token()

            new_token = generator.get_next_tokens()[0]
            print(tokenizer_stream.decode(new_token), end='', flush=True)
    except KeyboardInterrupt:
        print("  --control+c pressed, aborting generation--")

    print()
    text = input("Input: ")
```
