### ISSUE TITLE
Phi3 example error  evaluators -> common_evaluator   gqa_transformer_prompt_dummy_data not found in {} (type=value_error)

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/Olive#1447]
**Olive logs**
(Olive-Win) PS C:\repos\Olive-Win\Olive\examples\phi3> python phi3.py --target cpu --precision int4 --inference --prompt
 "Write a story starting with once upon a time" --max_length 200

Generating Olive configuration file...
Olive configuration file is generated...

Generating optimized model for cpu ...

Traceback (most recent call last):
  File "C:\repos\Olive-Win\Olive\examples\phi3\phi3.py", line 352, in <module>
    main()
  File "C:\repos\Olive-Win\Olive\examples\phi3\phi3.py", line 167, in main
    olive_run(run_config)
  File "C:\repos\Olive-Win\lib\site-packages\olive\workflows\run\run.py", line 292, in run
    run_config: RunConfig = RunConfig.parse_file_or_obj(run_config)
  File "C:\repos\Olive-Win\lib\site-packages\olive\common\config_utils.py", line 119, in parse_file_or_obj
    return cls.parse_obj(file_or_obj)
  File "C:\repos\Olive-Win\lib\site-packages\pydantic\v1\main.py", line 526, in parse_obj
    return cls(**obj)
  File "C:\repos\Olive-Win\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for RunConfig
evaluators -> common_evaluator
  gqa_transformer_prompt_dummy_data not found in {} (type=value_error)

**Other information**
 - OS: Windows ARM64  (Python 3.10.11 x64 [not ARM])
 - Olive version: installed from source per: https://github.com/microsoft/Olive/tree/main/examples
 - ONNXRuntime onxxruntime 1.19.2
 - Transformers package version: 4.46.1

**Additional context**
Also tried creating a config file for cpu with python phi3.py --target cpu
This command creates a phi3_run_cpu_int4.json file, but produces the same error.

**Comment by jambayk** [comment]
Hi, thanks for pointing this out. This example was broken by a recent commit. I have proposed a fix in #1452
