### ISSUE TITLE
Missing Keras in requirements.txt

### ISSUE THREAD

**Issue by vcollette** [microsoft/OLive#15]
onnx-converter `requirements.txt` should install keras

 ```
{'conversion_status': 'FAILED',

 'correctness_verified': 'FAILED',

 'error_message': "No module named 'keras'",

 'input_folder': '',

 'output_onnx_path': ''}

Traceback (most recent call last):

  File "src/onnx_converter.py", line 343, in <module>

    main()

  File "src/onnx_converter.py", line 309, in main

    raise e

  File "src/onnx_converter.py", line 299, in main

    convert_models(args)

  File "src/onnx_converter.py", line 277, in convert_models

    converter(args)

  File "src/onnx_converter.py", line 150, in keras2onnx

    import keras

ModuleNotFoundError: No module named 'keras'
```

**Comment by liuziyue** [comment]
Fixed in #16
