### ISSUE TITLE
[Bug]:  AssertionError: No valid accelerator specified for target system.

### ISSUE THREAD

**Issue by CuttlefishJones** [microsoft/Olive#323]
### What happened?

Followed the intructions at: https://github.com/microsoft/Olive/tree/main/examples/directml/stable_diffusion

When running - 'python stable_diffusion.py --optimize' the script dwnloaded the required files and then bugged out with the follwing error: 'AssertionError: No valid accelerator specified for target system.'

Here is output from DXDiag

[DxDiag.txt](https://github.com/microsoft/Olive/files/11666678/DxDiag.txt)

### Version?

v0.2.1

**Comment by xiaoyu-work** [comment]
As for GPU accelerator, Olive doesn't support AMD yet. Olive supports `DmlExecutionProvider, CUDAExecutionProvider, OpenVINOExecutionProvider, TensorrtExecutionProvider, CPUExecutionProvider` for GPU accelerator. Please either remove the `"accelerators": ["gpu"]` in config json (it will default to cpu), or use `"accelerators": ["cpu"]` instead.

**Comment by CuttlefishJones** [comment]
Yes I did.

**Comment by xiaoyu-work** [comment]
What is the output if you run
```
import onnxruntime
available_providers = onnxruntime.get_available_providers()
print(available_providers )
```
in your environment?

**Comment by guotuofeng** [comment]
@CuttlefishJones , would you please provide the info @xiaoyu-work asked?

**Comment by NeedsMoar** [comment]
I had this problem when I had installed plain onnxruntime & onnxruntime-gpu first (in that order), apparently installing onnxruntime-directml after those will add directml.dll but never update the list of providers somehow. This post was useful, my list was:
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

I had to uninstall all 3 providers (removing the regular and GPU variants also removed all of the onnxruntime python so your commands above failed) then install onnxruntime-directml by itself to fix it.  
After that I had:
['DMLExecutionProvider', 'CPUExecutionProvider']

and the example is currently optimizing a model.  Not the reporter but I suspect it's the same issue.

**Comment by guotuofeng** [comment]
Yeah, before installing onnxruntime-directml, all other onnxruntime need to be manually uninstalled since they cannot co-exist.

**Comment by guotuofeng** [comment]
close this issue since there is no response for long time

**Comment by khmyznikov** [comment]
@guotuofeng @jambayk
```
Olive on  main [?⇣] via 🐍 v3.11.6 (whisper) 
❯ pip install onnxruntime-directml
Requirement already satisfied: onnxruntime-directml in c:\users\user\develop\python\whisper\lib\site-packages (1.16.3)
Requirement already satisfied: coloredlogs in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (23.5.26)
Requirement already satisfied: numpy>=1.24.2 in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (1.26.2)
Requirement already satisfied: packaging in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (23.2)
Requirement already satisfied: protobuf in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (3.20.3)
Requirement already satisfied: sympy in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\user\develop\python\whisper\lib\site-packages (from coloredlogs->onnxruntime-directml) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\user\develop\python\whisper\lib\site-packages (from sympy->onnxruntime-directml) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\user\develop\python\whisper\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-directml) (3.4.1)

Olive on  main [?⇣] via 🐍 v3.11.6 (whisper) took 2s
❯ & C:/Users/user/Develop/Python/whisper/Scripts/python.exe c:/Users/user/Develop/GitHub/Olive/examples/whisper/providers_list.py
['DmlExecutionProvider', 'CPUExecutionProvider']

Olive on  main [?⇣] via 🐍 v3.11.6 (whisper) 
❯ cd .\examples\whisper\

Olive\examples\whisper on  main [?⇣] via 🐍 v3.11.6 (whisper) 
❯ python -m olive.workflows.run --config whisper_gpu_fp16.json --setup
[2023-11-21 15:49:33,754] [DEBUG] [engine.py:123:setup_accelerators] Initial execution providers: ['CUDAExecutionProvider']
[2023-11-21 15:49:33,754] [DEBUG] [engine.py:141:setup_accelerators] Initial accelerators: ['gpu']
[2023-11-21 15:49:33,754] [DEBUG] [engine.py:162:setup_accelerators] Supported execution providers for device gpu: ['DmlExecutionProvider', 'CPUExecutionProvider']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\__main__.py", line 28, in <module>
    run(**var_args)
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\run.py", line 161, in run
    engine = config.engine.create_engine()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\config.py", line 55, in create_engine
    return Engine(config)
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\engine\engine.py", line 83, in __init__
    self.setup_accelerators(execution_providers)
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\engine\engine.py", line 172, in setup_accelerators
    assert self.accelerator_specs, (
AssertionError: No valid accelerator specified for target system. Please specify the accelerators in the target system or provide valid execution providers. Given execution providers: ['CUDAExecutionProvider']. Current accelerators: ['gpu'].Supported execution providers: {'cpu': ['CPUExecutionProvider', 'OpenVINOExecutionProvider'], 'gpu': ['DmlExecutionProvider', 'CUDAExecutionProvider', 'ROCMExecutionProvider', 'TensorrtExecutionProvider', 'CPUExecutionProvider', 'OpenVINOExecutionProvider'], 'npu': ['QNNExecutionProvider', 'CPUExecutionProvider']}.
```

**Comment by guotuofeng** [comment]
@khmyznikov, Thanks for raising the issue. This is a bug. the attached PR should fix it.

**Comment by guotuofeng** [comment]
@khmyznikov the bug is fixed.

**Comment by khmyznikov** [comment]
@guotuofeng now it's different error:
```
Olive\examples\whisper on  main [?⇣] via 🐍 v3.11.6 (whisper) 
❯ pip install onnxruntime-directml
Requirement already satisfied: onnxruntime-directml in c:\users\user\develop\python\whisper\lib\site-packages (1.16.3)
Requirement already satisfied: coloredlogs in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (23.5.26)
Requirement already satisfied: numpy>=1.24.2 in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (1.26.2)
Requirement already satisfied: packaging in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (23.2)
Requirement already satisfied: protobuf in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (3.20.3)
Requirement already satisfied: sympy in c:\users\user\develop\python\whisper\lib\site-packages (from onnxruntime-directml) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\user\develop\python\whisper\lib\site-packages (from coloredlogs->onnxruntime-directml) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\user\develop\python\whisper\lib\site-packages (from sympy->onnxruntime-directml) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\user\develop\python\whisper\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-directml) (3.4.1)

Olive\examples\whisper on  main [?⇣] via 🐍 v3.11.6 (whisper) took 2s 
❯ & C:/Users/user/Develop/Python/whisper/Scripts/python.exe c:/Users/user/Develop/GitHub/Olive/examples/whisper/providers_list.py
['DmlExecutionProvider', 'CPUExecutionProvider']

Olive\examples\whisper on  main [?⇣] via 🐍 v3.11.6 (whisper) 
❯ python -m olive.workflows.run --config whisper_gpu_fp16.json --setup
[2023-11-22 16:21:40,879] [INFO] [run.py:119:dependency_setup] The following packages are required in the local environment: ['onnxruntime-gpu']
[2023-11-22 16:21:40,951] [WARNING] [run.py:249:check_local_ort_installation] There are one or more onnxruntime packages installed in your environment!
The setup process is stopped to avoid potential conflicts. Please run the following commands manually:
Uninstall all existing onnxruntime packages: 'python -m pip uninstall -y onnxruntime-directml'
Install onnxruntime-gpu: 'python -m pip install onnxruntime-gpu'
You can also instead install the corresponding nightly version following the instructions at https://onnxruntime.ai/docs/install/#inference-install-table-for-all-languages
```

**Comment by khmyznikov** [comment]
```
Administrator in Olive\examples\whisper on  main [?] via 🐍 v3.11.6 (whisper) took 5s
❯ python -m olive.workflows.run --config whisper_gpu_fp16.json
[2023-11-22 16:46:33,955] [WARNING] [config_utils.py:308:validate_config] Keys {'log_to_file'} are not part of EngineConfig. Ignoring them.
[2023-11-22 16:46:33,956] [DEBUG] [engine.py:123:setup_accelerators] Initial execution providers: ['CUDAExecutionProvider']
[2023-11-22 16:46:33,956] [DEBUG] [engine.py:141:setup_accelerators] Initial accelerators: ['gpu']
[2023-11-22 16:46:33,956] [DEBUG] [engine.py:162:setup_accelerators] Supported execution providers for device gpu: ['DmlExecutionProvider', 'CPUExecutionProvider']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\__main__.py", line 28, in <module>
    run(**var_args)
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\run.py", line 209, in run
    return run_engine(config, data_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\run.py", line 150, in run_engine
    engine = config.engine.create_engine()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\workflows\run\config.py", line 56, in create_engine
    return Engine(config)
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\engine\engine.py", line 83, in __init__
    self.setup_accelerators(execution_providers)
  File "C:\Users\user\Develop\Python\whisper\Lib\site-packages\olive\engine\engine.py", line 172, in setup_accelerators
    assert self.accelerator_specs, (
AssertionError: No valid accelerator specified for target system. Please specify the accelerators in the target system or provide valid execution providers. Given execution providers: ['CUDAExecutionProvider']. Current accelerators: ['gpu'].Supported execution providers: {'cpu': ['CPUExecutionProvider', 'OpenVINOExecutionProvider'], 'gpu': ['DmlExecutionProvider', 'CUDAExecutionProvider', 'ROCMExecutionProvider', 'TensorrtExecutionProvider', 'CPUExecutionProvider', 'OpenVINOExecutionProvider'], 'npu': ['QNNExecutionProvider', 'CPUExecutionProvider']}.
```
