### ISSUE TITLE
[Bug]: not work Whisper optimization

### ISSUE THREAD

**Issue by YuriyKrasilnikov** [microsoft/Olive#438]
### What happened?

Tried to repeat the steps described in https://github.com/microsoft/Olive/tree/main/examples/whisper, unfortunately it doesn't work.

`python3 -m olive.workflows.run --config whisper_cpu_int8.json`

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/olive/workflows/run/__main__.py", line 16, in <module>
    run(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/olive/workflows/run/run.py", line 129, in run
    input_model = config.input_model.create_model()
  File "/usr/local/lib/python3.10/dist-packages/olive/model.py", line 167, in create_model
    return REGISTRY[self.type.lower()](**self.config)
  File "/usr/local/lib/python3.10/dist-packages/olive/model.py", line 558, in __init__
    self.hf_config = validate_config(hf_config, HFConfig) if hf_config else None
  File "/usr/local/lib/python3.10/dist-packages/olive/common/config_utils.py", line 242, in validate_config
    config = instance_class(**config)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for HFConfig
components -> 0 -> io_config
  value is not a valid dict (type=type_error.dict)
components -> 1 -> io_config
  value is not a valid dict (type=type_error.dict)`

### Version?

0.2.1

**Comment by xiaoyu-work** [comment]
Hi @YuriyKrasilnikov , our examples are usually updated to work with our latest changes. Can you please try the main branch?

**Comment by YuriyKrasilnikov** [comment]
> 

Hi @xiaoyu-work.
I just tried main branch.
Perhaps I can provide additional information so you can reproduce the error?

**Comment by xiaoyu-work** [comment]
@YuriyKrasilnikov can you please provide the steps how you install the Olive package and how you run the whisper example? Also can you please provide the new stacktrace? I believe the stacktrace you pasted before is not for the main branch Olive.

**Comment by YuriyKrasilnikov** [comment]
@xiaoyu-work big thank!
I installed from git instead of pip and it worked fine.
