### ISSUE TITLE
[Bug]: Doesn't work with openai/whisper-large-v2

### ISSUE THREAD

**Issue by YuriyKrasilnikov** [microsoft/Olive#448]
### What happened?

To reproduce the error:

With  examples/whisper
`python prepare_whisper_configs.py --model_name openai/whisper-large-v2 --multilingual`

When
`python -m olive.workflows.run --config whisper_cpu_int8.json`

```
[2023-07-27 08:17:13,182] [DEBUG] [config.py:122:fill_in_params] Missing parameter data_dir for component load_dataset
[2023-07-27 08:17:13,192] [DEBUG] [engine.py:618:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-07-27 08:17:13,192] [DEBUG] [engine.py:637:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-07-27 08:17:13,192] [DEBUG] [engine.py:436:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'OnnxDynamicQuantization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-07-27 08:17:13,192] [INFO] [engine.py:882:_run_pass] Running pass OnnxConversion
[2023-07-27 08:17:13,193] [DEBUG] [engine.py:890:_run_pass] Loading model from cache ...
[2023-07-27 08:17:13,196] [INFO] [engine.py:882:_run_pass] Running pass OrtTransformersOptimization
[2023-07-27 08:17:13,197] [DEBUG] [engine.py:744:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
[2023-07-27 08:17:18,135] [ERROR] [engine.py:942:_run_pass] Pass run failed.
Traceback (most recent call last):
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/engine/engine.py", line 930, in _run_pass
    output_model = host.run_pass(p, input_model, data_root, output_model_path, pass_search_point)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/systems/local.py", line 33, in run_pass
    return the_pass.run(model, data_root, output_model_path, point)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/passes/olive_pass.py", line 391, in run
    components.append(self._run_for_config(child, data_root, config, str(component_output_path)))
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/passes/onnx/transformer_optimization.py", line 104, in _run_for_config
    optimizer = transformers_optimizer.optimize_model(input=model.model_path, **run_config)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnxruntime/transformers/optimizer.py", line 323, in optimize_model
    model = load_model(temp_model_path or input)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/__init__.py", line 176, in load_model
    load_external_data_for_model(model, base_dir)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 65, in load_external_data_for_model
    load_external_data_for_tensor(tensor, base_dir)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 45, in load_external_data_for_tensor
    with open(external_data_file_path, "rb") as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9o2iozdo/model.onnx.data'
[2023-07-27 08:17:18,135] [WARNING] [engine.py:362:run] Failed to run Olive on cpu-cpu: [Errno 2] No such file or directory: '/tmp/tmp9o2iozdo/model.onnx.data'
Traceback (most recent call last):
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/engine/engine.py", line 337, in run
    output = self.run_no_search(
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/engine/engine.py", line 443, in run_no_search
    ) = self._run_passes(next_step["passes"], model, model_id, data_root, accelerator_spec)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/engine/engine.py", line 845, in _run_passes
    model, model_id = self._run_pass(pass_id, pass_search_point, model, model_id, data_root, accelerator_spec)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/engine/engine.py", line 930, in _run_pass
    output_model = host.run_pass(p, input_model, data_root, output_model_path, pass_search_point)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/systems/local.py", line 33, in run_pass
    return the_pass.run(model, data_root, output_model_path, point)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/passes/olive_pass.py", line 391, in run
    components.append(self._run_for_config(child, data_root, config, str(component_output_path)))
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/olive/passes/onnx/transformer_optimization.py", line 104, in _run_for_config
    optimizer = transformers_optimizer.optimize_model(input=model.model_path, **run_config)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnxruntime/transformers/optimizer.py", line 323, in optimize_model
    model = load_model(temp_model_path or input)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/__init__.py", line 176, in load_model
    load_external_data_for_model(model, base_dir)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 65, in load_external_data_for_model
    load_external_data_for_tensor(tensor, base_dir)
  File "/home/ykrasilnikov/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 45, in load_external_data_for_tensor
    with open(external_data_file_path, "rb") as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9o2iozdo/model.onnx.data'
[2023-07-27 08:17:18,144] [INFO] [engine.py:365:run] Package top ranked 0 models as artifacts
[2023-07-27 08:17:18,144] [WARNING] [packaging_generator.py:35:generate_output_artifacts] No model is selected. Skip packaging output artifacts.
```

### Version?

Name: olive-ai
Version: 0.3.0
Summary: Olive is an easy-to-use hardware-aware model optimization tool that composes industry-leading techniques across model compression, optimization, and compilation.
Home-page: https://microsoft.github.io/Olive/
Author: Microsoft Corporation
Author-email: olivedevteam@microsoft.com
License: MIT License
Location: /home/ykrasilnikov/.local/lib/python3.10/site-packages
Requires: numpy, onnx, optuna, pandas, protobuf, pydantic, pyyaml, torch, torchmetrics, transformers
Required-by:

#  freeze
alembic==1.11.1
attrs==21.2.0
Automat==20.2.0
Babel==2.8.0
bcrypt==3.2.0
blinker==1.4
build==0.10.0
certifi==2020.6.20
chardet==4.0.0
click==8.0.3
cloud-init==23.2.1
cmaes==0.10.0
cmake==3.27.0
colorama==0.4.4
coloredlogs==15.0.1
colorlog==6.7.0
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contextlib2==21.6.0
contourpy==1.1.0
cryptography==3.4.8
cycler==0.11.0
dbus-python==1.2.18
Deprecated==1.2.14
distro==1.7.0
distro-info===1.1build1
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.1
fsspec==2023.6.0
greenlet==2.0.2
httplib2==0.20.2
huggingface-hub==0.16.4
humanfriendly==10.0
hyperlink==21.0.0
idna==3.3
importlib-metadata==4.6.4
incremental==21.3.0
jeepney==0.7.1
Jinja2==3.0.3
joblib==1.3.1
jsonpatch==1.32
jsonpointer==2.0
jsonschema==3.2.0
keyring==23.5.0
kiwisolver==1.4.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lit==16.0.6
Mako==1.2.4
MarkupSafe==2.0.1
matplotlib==3.7.2
more-itertools==8.10.0
mpmath==1.3.0
netifaces==0.11.0
networkx==3.1
neural-compressor==2.2.1
numpy==1.25.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.0
olive-ai @ file:///home/ykrasilnikov/Olive
onnx==1.14.0
onnxruntime-extensions==0.8.0
opencv-python-headless==4.8.0.74
optuna==3.2.0
ort-nightly==1.16.0.dev20230725005
packaging==23.1
pandas==2.0.3
pexpect==4.8.0
Pillow==10.0.0
pip-tools==7.1.0
prettytable==3.8.0
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
py-cpuinfo==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycocotools==2.0.6
pydantic==1.10.12
PyGObject==3.42.1
PyHamcrest==2.0.2
PyJWT==2.3.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyproject_hooks==1.0.0
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.2
python-debian==0.1.43+ubuntu1.1
python-magic==0.4.24
pytz==2022.1
PyYAML==5.4.1
regex==2023.6.3
requests==2.25.1
safetensors==0.3.1
schema==0.7.5
scikit-learn==1.3.0
scipy==1.11.1
SecretStorage==3.3.1
service-identity==18.1.0
six==1.16.0
sos==4.4
SQLAlchemy==2.0.19
ssh-import-id==5.11
sympy==1.12
systemd-python==234
threadpoolctl==3.2.0
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.1
torchmetrics==0.10.0
tqdm==4.65.0
transformers==4.31.0
triton==2.0.0
Twisted==22.1.0
typing_extensions==4.7.1
tzdata==2023.3
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
wadllib==1.3.6
wcwidth==0.2.6
wrapt==1.15.0
xkit==0.0.0
zipp==1.0.0
zope.interface==5.4.0

**Comment by guotuofeng** [comment]
Hi, @YuriyKrasilnikov 

I think you hit the bug introduced by ORT fixes to move intermediate model from model source folder into temp folder for model with external data. (https://github.com/microsoft/onnxruntime/pull/16716)

Once the ORT with above PR is release, Olive need specify use_external_data_format=True at https://github.com/microsoft/Olive/blob/main/olive/passes/onnx/transformer_optimization.py#L104C44-L104C58

From the time being, there are two work around for the issues:
1. use the official onnxruntime 1.15.1
2. if you would like to use ort nightly build, would you please add use_external_data_format=True in Olive code mentioned in above link?

**Comment by xiaoyu-work** [comment]
Hi @YuriyKrasilnikov , this is a known issue from ort-nightly. We are still fixing this. Can you try a different ort-nightly version? `python -m pip install ort-nightly==1.16.0.dev20230629002 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/`

**Comment by YuriyKrasilnikov** [comment]
@xiaoyu-work thank you!!!
It works!!!
