### ISSUE TITLE
[Bug]: INVALID_GRAPH /  Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10] when trying to build a non-openai provided Whisper model.

### ISSUE THREAD

**Issue by vmitro** [microsoft/Olive#508]
### What happened?

When trying to build an ONNX model without multilingual support, using instructions on the [whisper example](https://github.com/microsoft/Olive/blob/main/examples/whisper/README.md) page and supplying a non-openai repo (e.g. aware-ai/whisper-tiny-german) the `test_transcription.py` fails. Tested using venv.

```
(olive-env) (base) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ python prepare_whisper_configs.py --model_name aware-ai/whisper-tiny-german --no_audio_decoder
(olive-env) (base) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ python -m olive.workflows.run --config whisper_cpu_int8.json --setup
[2023-08-23 23:43:57,572] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-08-23 23:43:57,572] [INFO] [run.py:116:dependency_setup] onnxruntime is already installed.
(olive-env) (base) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ python -m olive.workflows.run --config whisper_cpu_int8.json
[2023-08-23 23:44:07,042] [WARNING] [config_utils.py:270:validate_config] Keys {'disable_search'} are not part of OrtTransformersOptimizationConfig. Ignoring them.
[2023-08-23 23:44:07,077] [DEBUG] [engine.py:675:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-08-23 23:44:07,077] [DEBUG] [engine.py:694:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-08-23 23:44:07,078] [DEBUG] [engine.py:475:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'OnnxDynamicQuantization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-08-23 23:44:07,078] [INFO] [engine.py:939:_run_pass] Running pass OnnxConversion
[2023-08-23 23:44:07,078] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-23 23:44:07,082] [INFO] [engine.py:939:_run_pass] Running pass OrtTransformersOptimization
[2023-08-23 23:44:07,083] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-23 23:44:07,087] [INFO] [engine.py:939:_run_pass] Running pass OnnxDynamicQuantization
[2023-08-23 23:44:07,087] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-23 23:44:07,091] [INFO] [engine.py:939:_run_pass] Running pass InsertBeamSearch
[2023-08-23 23:44:07,092] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-23 23:44:07,093] [INFO] [engine.py:939:_run_pass] Running pass AppendPrePostProcessingOps
[2023-08-23 23:44:07,094] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-23 23:44:07,095] [DEBUG] [engine.py:1076:_evaluate_model] Evaluating model ...
[2023-08-23 23:44:07,096] [DEBUG] [engine.py:1087:_evaluate_model] Loading evaluation from cache ...
[2023-08-23 23:44:07,096] [DEBUG] [engine.py:917:_run_passes] Signal: {'latency-avg': 1079.78704}
[2023-08-23 23:44:07,096] [DEBUG] [engine.py:499:run_no_search] Engine output_name is provided. Will ignore output_name for final pass
[2023-08-23 23:44:07,227] [INFO] [engine.py:384:run] Package top ranked 1 models as artifacts
[2023-08-23 23:44:07,227] [INFO] [packaging_generator.py:47:_generate_zipfile_output] Packaging Zipfile output artifacts
[2023-08-23 23:44:07,281] [DEBUG] [resource_path.py:147:create_resource_path] Resource path /tmp/tmpq7o_oxgh/CandidateModels/cpu-cpu/BestCandidateModel_1/olive_tmpkcdwbdnu/model.onnx is inferred to be of type file.
[2023-08-23 23:44:07,288] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime-extensions==0.8.0 --no-deps -d /tmp/tmpq7o_oxgh/ONNXRuntimePackages/Python with env: None
[2023-08-23 23:44:08,206] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime==1.15.1 --no-deps -d /tmp/tmpq7o_oxgh/ONNXRuntimePackages/Python with env: None
(olive-env) (base) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ python test_transcription.py --config whisper_cpu_int8.json
> /home/vmitro/projects/olive_stuff/Olive/examples/whisper/test_transcription.py(71)main()
-> for model_json in output_model_json_path.glob(f"**/{config['engine']['output_name']}_cpu-cpu_model.json"):
[2023-08-23 23:45:27,367] [WARNING] [__init__.py:212:_is_valid_ep] Error: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /home/vmitro/projects/olive_stuff/Olive/examples/whisper/models/conversion-transformers_optimization-onnx_dynamic_quantization-insert_beam_search-prepost/whisper_cpu_int8_cpu-cpu_model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].Olive will ignore this CPUExecutionProvider.Please make sure the environment with CPUExecutionProvider has the required dependencies.
Traceback (most recent call last):
  File "/home/vmitro/projects/olive_stuff/Olive/examples/whisper/test_transcription.py", line 108, in <module>
    output_text = main()
  File "/home/vmitro/projects/olive_stuff/Olive/examples/whisper/test_transcription.py", line 98, in main
    session = olive_model.prepare_session(None, "cpu")
  File "/home/vmitro/projects/olive_stuff/olive-env/lib/python3.10/site-packages/olive/model/__init__.py", line 346, in prepare_session
    return get_ort_inference_session(self.model_path, inference_settings, self.use_ort_extensions)
  File "/home/vmitro/projects/olive_stuff/olive-env/lib/python3.10/site-packages/olive/common/ort_inference.py", line 64, in get_ort_inference_session
    sess = ort.InferenceSession(
  File "/home/vmitro/projects/olive_stuff/olive-env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/vmitro/projects/olive_stuff/olive-env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /home/vmitro/projects/olive_stuff/Olive/examples/whisper/models/conversion-transformers_optimization-onnx_dynamic_quantization-insert_beam_search-prepost/whisper_cpu_int8_cpu-cpu_model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].
```

When installing the latest onnxruntime (1.16.0-dev*) through `python -m pip install ort-nightly --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/` the transcription seems to work (haven't tested with a audio file with spoken German, but the supplied file gets transcribed into a German-looking text).

When loaded into the Android ONNX Runtime (latest ver 1.15.1) I get exactly the same error. When I compare the two repos' `config.json` files ([openai's](https://huggingface.co/openai/whisper-tiny/blob/main/config.json) and [the aforementioned](https://huggingface.co/aware-ai/whisper-base-german/blob/main/config.json)), some `decoder_*` and `encoder_*` options differ.

Could this be a ONNX Runtime bug? I'm currently building Android runtime from source, will report if I get it to work using my build.

### Version?

Olive: 0.3.1
ONNX Runtime: 1.15.1

**Comment by jambayk** [comment]
This is because of the mismatch between the versions of the onnxruntime versions used to build the model and run it. The beam search node has changed between the stable 1.15.1 version and the nightly version. 

Hence, this error `Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].`

If you don't need multilingual support (for instance your model is finetuned on german so it always produces german text), please run the workflow again with onnxruntime 1.15.1 installed. 

If you need multilingual support, then the workflow must be run with onnxruntime nightly and your the onnxruntime used for inference must also be nightly (or built from source)

**Comment by vmitro** [comment]
Well, interestingly, that seems not to be that case.

After creating a Python 3.8 conda environment, building Olive from source like [here](https://github.com/microsoft/Olive/blob/main/examples/README.md) and then running a bash script to take the model name from an env variable and run through the steps to compile a CPU/INT8 model, I got the same error.

```
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ export MODEL_NAME=aware-ai/whisper-tiny-german
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ ./maek_model.sh
[2023-08-24 09:53:18,802] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-08-24 09:53:18,802] [INFO] [run.py:116:dependency_setup] onnxruntime is already installed.
[2023-08-24 09:53:21,758] [WARNING] [config_utils.py:270:validate_config] Keys {'disable_search'} are not part of OrtTransformersOptimizationConfig. Ignoring them.
[2023-08-24 09:53:21,792] [DEBUG] [engine.py:675:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-08-24 09:53:21,793] [DEBUG] [engine.py:694:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-08-24 09:53:21,793] [DEBUG] [engine.py:475:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'OnnxDynamicQuantization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-08-24 09:53:21,793] [INFO] [engine.py:939:_run_pass] Running pass OnnxConversion
[2023-08-24 09:53:21,793] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:53:21,797] [INFO] [engine.py:939:_run_pass] Running pass OrtTransformersOptimization
[2023-08-24 09:53:21,798] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:53:21,802] [INFO] [engine.py:939:_run_pass] Running pass OnnxDynamicQuantization
[2023-08-24 09:53:21,803] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:53:21,807] [INFO] [engine.py:939:_run_pass] Running pass InsertBeamSearch
[2023-08-24 09:53:21,807] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:53:21,810] [INFO] [engine.py:939:_run_pass] Running pass AppendPrePostProcessingOps
[2023-08-24 09:53:21,810] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:53:21,812] [DEBUG] [engine.py:1076:_evaluate_model] Evaluating model ...
[2023-08-24 09:53:21,812] [DEBUG] [engine.py:1087:_evaluate_model] Loading evaluation from cache ...
[2023-08-24 09:53:21,813] [DEBUG] [engine.py:917:_run_passes] Signal: {'latency-avg': 1079.78704}
[2023-08-24 09:53:21,813] [DEBUG] [engine.py:499:run_no_search] Engine output_name is provided. Will ignore output_name for final pass
[2023-08-24 09:53:21,897] [INFO] [engine.py:384:run] Package top ranked 1 models as artifacts
[2023-08-24 09:53:21,897] [INFO] [packaging_generator.py:47:_generate_zipfile_output] Packaging Zipfile output artifacts
[2023-08-24 09:53:21,968] [DEBUG] [resource_path.py:147:create_resource_path] Resource path /tmp/tmpfjp241j3/CandidateModels/cpu-cpu/BestCandidateModel_1/olive_tmpq4g6kd86/model.onnx is inferred to be of type file.
[2023-08-24 09:53:21,976] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime-extensions==0.8.0 --no-deps -d /tmp/tmpfjp241j3/ONNXRuntimePackages/Python with env: None
[2023-08-24 09:53:22,788] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime==1.15.1 --no-deps -d /tmp/tmpfjp241j3/ONNXRuntimePackages/Python with env: None
[2023-08-24 09:53:46,103] [WARNING] [__init__.py:212:_is_valid_ep] Error: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /home/vmitro/projects/olive_stuff/Olive/examples/whisper/models/conversion-transformers_optimization-onnx_dynamic_quantization-insert_beam_search-prepost/whisper_cpu_int8_cpu-cpu_model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].Olive will ignore this CPUExecutionProvider.Please make sure the environment with CPUExecutionProvider has the required dependencies.
Traceback (most recent call last):
  File "test_transcription.py", line 108, in <module>
    output_text = main()
  File "test_transcription.py", line 98, in main
    session = olive_model.prepare_session(None, "cpu")
  File "/home/vmitro/miniconda3/envs/olive/lib/python3.8/site-packages/olive/model/__init__.py", line 346, in prepare_session
    return get_ort_inference_session(self.model_path, inference_settings, self.use_ort_extensions)
  File "/home/vmitro/miniconda3/envs/olive/lib/python3.8/site-packages/olive/common/ort_inference.py", line 64, in get_ort_inference_session
    sess = ort.InferenceSession(
  File "/home/vmitro/miniconda3/envs/olive/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/vmitro/miniconda3/envs/olive/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /home/vmitro/projects/olive_stuff/Olive/examples/whisper/models/conversion-transformers_optimization-onnx_dynamic_quantization-insert_beam_search-prepost/whisper_cpu_int8_cpu-cpu_model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].
```
```
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ export MODEL_NAME=aware-ai/whisper-base-german
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ ./maek_model.sh
[2023-08-24 09:55:29,475] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-08-24 09:55:29,475] [INFO] [run.py:116:dependency_setup] onnxruntime is already installed.
[2023-08-24 09:55:32,336] [WARNING] [config_utils.py:270:validate_config] Keys {'disable_search'} are not part of OrtTransformersOptimizationConfig. Ignoring them.
[2023-08-24 09:55:32,366] [DEBUG] [engine.py:675:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-08-24 09:55:32,366] [DEBUG] [engine.py:694:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-08-24 09:55:32,366] [DEBUG] [engine.py:475:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'OnnxDynamicQuantization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-08-24 09:55:32,367] [INFO] [engine.py:939:_run_pass] Running pass OnnxConversion
[2023-08-24 09:55:32,367] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:55:32,371] [INFO] [engine.py:939:_run_pass] Running pass OrtTransformersOptimization
[2023-08-24 09:55:32,372] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:55:32,376] [INFO] [engine.py:939:_run_pass] Running pass OnnxDynamicQuantization
[2023-08-24 09:55:32,376] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:55:32,381] [INFO] [engine.py:939:_run_pass] Running pass InsertBeamSearch
[2023-08-24 09:55:32,381] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:55:32,383] [INFO] [engine.py:939:_run_pass] Running pass AppendPrePostProcessingOps
[2023-08-24 09:55:32,383] [DEBUG] [engine.py:957:_run_pass] Loading model from cache ...
[2023-08-24 09:55:32,385] [DEBUG] [engine.py:1076:_evaluate_model] Evaluating model ...
[2023-08-24 09:55:32,385] [DEBUG] [engine.py:1087:_evaluate_model] Loading evaluation from cache ...
[2023-08-24 09:55:32,385] [DEBUG] [engine.py:917:_run_passes] Signal: {'latency-avg': 1396.85263}
[2023-08-24 09:55:32,386] [DEBUG] [engine.py:499:run_no_search] Engine output_name is provided. Will ignore output_name for final pass
[2023-08-24 09:55:32,511] [INFO] [engine.py:384:run] Package top ranked 1 models as artifacts
[2023-08-24 09:55:32,511] [INFO] [packaging_generator.py:47:_generate_zipfile_output] Packaging Zipfile output artifacts
[2023-08-24 09:55:32,632] [DEBUG] [resource_path.py:147:create_resource_path] Resource path /tmp/tmpk6ssiia2/CandidateModels/cpu-cpu/BestCandidateModel_1/olive_tmpx24pxtyp/model.onnx is inferred to be of type file.
[2023-08-24 09:55:32,640] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime-extensions==0.8.0 --no-deps -d /tmp/tmpk6ssiia2/ONNXRuntimePackages/Python with env: None
[2023-08-24 09:55:33,419] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime==1.15.1 --no-deps -d /tmp/tmpk6ssiia2/ONNXRuntimePackages/Python with env: None
['Gedownes Church ist durch Wimbledd, dieÄquem ist, oberstehende Eis, eventuell in der Arena, Roundham, wird zuvor nicht im Speck gedurch, und für die Arreby ist noch was dünktig gebaut.']
```
However, as you can see, running the same steps with another model (the base variant) seems to work - the only problem being, it is really heavy and I must put `android:largeHeap="true"` inside my app's `AndroidManifest.xml`. On the other side, the base version is noticeably better at recognition.

The onnxruntime's version remained the same between the two invocations.

```
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ pip show onnxruntime
Name: onnxruntime
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /home/vmitro/miniconda3/envs/olive/lib/python3.8/site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by:
```

Here's the listing of the simple bash script used:
```
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ cat maek_model.sh
```
```
#!/bin/bash

if [ -z "$MODEL_NAME" ]; then
    echo "Run $ export MODEL_NAME=repo/model-name to run automated conversion to CPU with INT8!"
    exit 1
fi

python prepare_whisper_configs.py --model_name $MODEL_NAME --no_audio_decoder && \
python -m olive.workflows.run --config whisper_cpu_int8.json --setup && \
python -m olive.workflows.run --config whisper_cpu_int8.json 2> /dev/null
if [ $? -eq 0 ]; then
    python test_transcription.py --config whisper_cpu_int8.json
else
    echo "Model conversion failed"
fi
```

I am going to try it (yet) again, this time with pip's olive_ai package. Will report my findings.

**Comment by jambayk** [comment]
Oh that's because it is using a cached run as none of the configs changed. Your original run with the nightly version must have been cached. 
![image](https://github.com/microsoft/Olive/assets/94929125/92f66672-39ce-44cf-9934-c01867931807)


Can you run the workflow again after deleting the `cache` subdir in your working directory? 
You can also set `"clean_cache": true` under `engine` in the `whisper_template.json` to do the same. 

Can you try again with this change?

**Comment by vmitro** [comment]
That did the trick, thank you very much!

```
(olive) vmitro@v3629:~/projects/olive_stuff/Olive/examples/whisper$ MODEL_NAME=aware-ai/whisper-tiny-german ./maek_model.sh
[2023-08-24 20:46:15,803] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-08-24 20:46:15,803] [INFO] [run.py:116:dependency_setup] onnxruntime is already installed.
[2023-08-24 20:46:18,698] [WARNING] [config_utils.py:270:validate_config] Keys {'disable_search'} are not part of OrtTransformersOptimizationConfig. Ignoring them.
[2023-08-24 20:46:18,722] [DEBUG] [engine.py:675:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-08-24 20:46:18,722] [DEBUG] [engine.py:694:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-08-24 20:46:18,723] [DEBUG] [engine.py:475:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'OnnxDynamicQuantization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-08-24 20:46:18,723] [INFO] [engine.py:939:_run_pass] Running pass OnnxConversion
[2023-08-24 20:46:18,723] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
[2023-08-24 20:46:24,445] [DEBUG] [__init__.py:570:get_dummy_inputs] Using dummy_inputs_func to get dummy inputs
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[2023-08-24 20:46:31,671] [DEBUG] [__init__.py:570:get_dummy_inputs] Using dummy_inputs_func to get dummy inputs
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[2023-08-24 20:46:33,604] [INFO] [engine.py:939:_run_pass] Running pass OrtTransformersOptimization
[2023-08-24 20:46:33,605] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
[2023-08-24 20:46:40,699] [INFO] [engine.py:939:_run_pass] Running pass OnnxDynamicQuantization
[2023-08-24 20:46:40,700] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
[2023-08-24 20:46:40,701] [INFO] [quantization.py:340:_run_for_config] Preprocessing model for quantization
[2023-08-24 20:46:50,864] [INFO] [quantization.py:340:_run_for_config] Preprocessing model for quantization
[2023-08-24 20:46:59,281] [INFO] [engine.py:939:_run_pass] Running pass InsertBeamSearch
[2023-08-24 20:46:59,282] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
Removed 40 initializers with duplicated value
Removed 24 initializers with duplicated value
[2023-08-24 20:47:03,356] [DEBUG] [insert_beam_search.py:140:chain_model] Using IR version 8 for chained model
[2023-08-24 20:47:03,817] [INFO] [engine.py:939:_run_pass] Running pass AppendPrePostProcessingOps
[2023-08-24 20:47:03,817] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 1 WARNING 0 ERROR ========================
1 WARNING were not printed due to the log level.

[2023-08-24 20:47:07,605] [DEBUG] [engine.py:1076:_evaluate_model] Evaluating model ...
[2023-08-24 20:47:07,605] [DEBUG] [engine.py:801:_prepare_non_local_model] Model path is None, local or string name. No need to prepare
[2023-08-24 20:47:07,642] [DEBUG] [olive_evaluator.py:194:generate_metric_user_config_with_model_io] Model input shapes are not static. Cannot use inferred input shapes for creating dummy data. This will cause an error when creating dummy data for tuning.
[2023-08-24 20:47:07,643] [DEBUG] [resource_path.py:147:create_resource_path] Resource path /home/vmitro/projects/olive_stuff/Olive/examples/whisper/data is inferred to be of type folder.
[2023-08-24 20:47:29,114] [DEBUG] [engine.py:917:_run_passes] Signal: {'latency-avg': 662.4}
[2023-08-24 20:47:29,114] [DEBUG] [engine.py:499:run_no_search] Engine output_name is provided. Will ignore output_name for final pass
[2023-08-24 20:47:29,201] [INFO] [engine.py:384:run] Package top ranked 1 models as artifacts
[2023-08-24 20:47:29,201] [INFO] [packaging_generator.py:47:_generate_zipfile_output] Packaging Zipfile output artifacts
[2023-08-24 20:47:29,258] [DEBUG] [resource_path.py:147:create_resource_path] Resource path /tmp/tmpat5y95kv/CandidateModels/cpu-cpu/BestCandidateModel_1/olive_tmphlyxy0gl/model.onnx is inferred to be of type file.
[2023-08-24 20:47:29,260] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime-extensions==0.8.0 --no-deps -d /tmp/tmpat5y95kv/ONNXRuntimePackages/Python with env: None
[2023-08-24 20:47:30,118] [DEBUG] [utils.py:21:run_subprocess] Running command: python -m pip download onnxruntime==1.15.1 --no-deps -d /tmp/tmpat5y95kv/ONNXRuntimePackages/Python with env: None
['Der traditionlich trifft historisch den Worten, die echte wichtig sind, ebenso sollen ihre Erwährendung bezahlreichen Sprengen verbaut.']
```

It even ~~sounds~~ reads more German :D 

Sooo... because hot-swapping onnxruntime versions is not really the workflow that one would usually employ, I should just close the issue as completed. You could maybe add your tip about deleting cache or enabling the clean_cache to the [readme](https://github.com/microsoft/Olive/blob/main/examples/README.md), in case anyone gets stuck like I did?

**Comment by jambayk** [comment]
Yes, I will! I am planning to add a note about the versions mismatch and cleaning the cache to the readme. 

Someone else also had an issue with the ort versions mismatch. I suspect the cache thing will come up too. 
Thanks for reporting them!

**Comment by vmitro** [comment]
No problem, thank you for your timely responses!
