### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'models.gpt2'

### ISSUE THREAD

**Issue by akarym-sl** [microsoft/Olive#554]
### What happened?

Having the following dir structure
.
|-- models
|   |-- model.py
|-- olive_optimize
|   |-- config.json
|   |-- main.py
|   `-- user_script.py
|-- trained_models
|   |-- model.model

```python
# main.py
from olive.workflows import run as olive_run
olive_run("olive_optimize/config.json")
```

results in the following error:
```
Traceback (most recent call last):
  File "/home/ismail/src/bvs_train/btr/pytorch/latency_optimization/olive_optimize/main.py", line 1, in <module>
    from olive.workflows import run as olive_run
  File "/home/ismail/.local/lib/python3.11/site-packages/olive/workflows/__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "/home/ismail/.local/lib/python3.11/site-packages/olive/workflows/run/run.py", line 16, in <module>
    from olive.passes import Pass
  File "/home/ismail/.local/lib/python3.11/site-packages/olive/passes/__init__.py", line 6, in <module>
    from olive.passes.onnx import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ismail/.local/lib/python3.11/site-packages/olive/passes/onnx/__init__.py", line 9, in <module>
    from olive.passes.onnx.insert_beam_search import InsertBeamSearch
  File "/home/ismail/.local/lib/python3.11/site-packages/olive/passes/onnx/insert_beam_search.py", line 10, in <module>
    from onnxruntime.transformers.convert_generation import get_shared_initializers
  File "/home/ismail/.local/lib/python3.11/site-packages/onnxruntime/transformers/convert_generation.py", line 75, in <module>
    from models.gpt2.convert_to_onnx import main as convert_gpt2_to_onnx  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'models.gpt2'
```

config.json

```json
{
    "input_model":{
        "type": "PyTorchModel",
        "config":{
            "model_path": "trained_models/model.model",
            "io_config":{
                "input_names": ["input"],
                "output_names": ["output"],
                "dynamic_axes": {
                    "input": {"0":"batch", "3": "yaxis"}, 
                    "output": {"0":"batch", "1":"width"}
                }
            }
        }
    },
    "data_root": "somedataroot",
    "systems":{
        "local_system":{
            "type": "LocalSystem",
            "config":{
                "accelerators":["cpu"]
            }
        }
    },
    "evaluators":{
        "custom_evaluator":{
            "metrics":[{
                "name": "latency",
                "type":"custom",
                "sub_types":[{
                    "name": "latency_custom", 
                    "priority": 1, 
                    "higher_is_better" : false
                    }],
                "user_config":{
                    "user_script":"olive_optimize/user_script.py",
                    "batch_size": 1,
                    "dataloader_func": "create_dataloader",
                    "evaluate_func": "evaluate_latency"
                }
            }]
        }
    },
    "engine":{
        "clean_cache":true,
        "cache_dir": ".cache",
        "host": "local_system",
        "target": "local_system",
        "evaluator": "custom_evaluator"
    },
    "passes":{
        "onnx_conversion":{
            "type": "OnnxConversion",
            "config":{
                "target_opset":20
            }
        },
        "onnx_quantization": {
            "type": "OnnxQuantization",
            "config":{
                "weight_type":"QUInt8"
            }
        }
    },
    "pass_flows":[
        ["onnx_conversion", "onnx_quantization"]
    ]
} 
```

### Version?

0.3.1

**Comment by xiaoyu-work** [comment]
@akarym-sl you have a same module name `models` in your folder so the Python cannot get the correct `models` module from onnxruntime. Can you please rename your `models` folder to something else like `model_script`?

**Comment by akarym-sl** [comment]
@xiaoyu-work yes, the error is gone when I do

**Comment by akarym-sl** [comment]
However, I need to also modify the model save file somehow to work with the new directory. Is there no better way to avoid this issue?

**Comment by akarym-sl** [comment]
After saving the model not as the whole object, but only the state dict, the problem is no more. While I understand where the issue is coming from, this is my first time encountering the conflict between my directories and ones of a package. Therefore, I assume that there is a better way to implement this which avoids such conflicts.

**Comment by guotuofeng** [comment]
the namespace conflicts comes from the Python module implementation.
