### ISSUE TITLE
[Bug]: ImportError: DLL load failed while importing _C: The specified module could not be found.

### ISSUE THREAD

**Issue by Boymerk** [microsoft/Olive#556]
### What happened?

$ python stable_diffusion.py
Traceback (most recent call last):
  File "D:\Python\olive\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 17, in <module>
    from diffusers import DiffusionPipeline, OnnxRuntimeModel, OnnxStableDiffusionPipeline
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\accelerate\accelerator.py", line 33, in <module>
    import torch.utils.hooks as hooks
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\__init__.py", line 4, in <module>
    from .throughput_benchmark import ThroughputBenchmark
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\throughput_benchmark.py", line 2, in <module>
    import torch._C
ImportError: DLL load failed while importing _C: The specified module could not be found.

### Version?

Latest

**Comment by jambayk** [comment]
Hi, this issue comes from the installation of python in your environment and is not directly from `Olive`. 

Can you please try the steps in this FAQ? https://pytorch.org/docs/1.4.0/notes/windows.html#import-error

Since, it appears you are not using a conda environment. The relevant section should be the one after `As for the wheels package, ...`

**Comment by guotuofeng** [comment]
This is related to torch. It is not Olive issue.
