### ISSUE TITLE
[Bug]: Olive installs the stable GPU version of ORT even though the nightly GPU version of ORT is already installed

### ISSUE THREAD

**Issue by jsoto-gladia** [microsoft/Olive#557]
### What happened?

related to the issue [here](https://github.com/microsoft/onnxruntime/issues/17393)

**description**
It appears Olive installs the stable GPU version of ORT even though the nightly GPU version of ORT is already installed

**steps to reproduce**
On a v100s machine, I prepare my pyenv with :
```bash
jsoto@v100s:/$ git clone https://github.com/microsoft/Olive.git
jsoto@v100s:/Olive$ cd Olive/
jsoto@v100s:/Olive$ pyenv virtualenv 3.9 aceituna
jsoto@v100s:/Olive$ pyenv shell aceituna
```

When in aceituna pyenv, I install all the necessary packages with:
```bash
(aceituna) jsoto@v100s:/Olive$ cd examples/whisper
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip install -r requirements.txt
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip uninstall -y onnxruntime ort-nightly onnxruntime-gpu ort-nightly-gpu
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip install ort-nightly --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

When running the configuration preparation, I do:
```bash
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m olive.workflows.run --config whisper_gpu_fp32.json 
```
I see that Olive does not use my ort-nightly-gpu and install and uses onnxruntime-gpu;
```bash
 [2023-09-12 20:27:44,600] [DEBUG] [resource_path.py:151:create_resource_path] Resource path code is inferred to be of type folder. [2023-09-12 20:27:44,602] [DEBUG] [resource_path.py:151:create_resource_path] Resource path code/user_script.py is inferred to be of type file. [2023-09-12 20:27:44,606] [WARNING] [engine.py:140:__init__] The following execution provider is not supported: AzureExecutionProvider. Please consider installing an onnxruntime build that contains the relevant execution providers.  [2023-09-12 20:27:44,606] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime-gpu'] [2023-09-12 20:27:44,606] [INFO] [run.py:118:dependency_setup] Installing onnxruntime-gpu... Collecting onnxruntime-gpu Obtaining dependency information for onnxruntime-gpu from https://files.pythonhosted.org/packages/5c/0c/70575b46df32de18d99872c11ec17dc589a48095d6828892241e434d0adc/onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata Downloading onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB) Requirement already satisfied: coloredlogs in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (15.0.1) Requirement already satisfied: flatbuffers in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (23.5.26) Requirement already satisfied: numpy>=1.21.6 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (1.24.3) Requirement already satisfied: packaging in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (23.1) Requirement already satisfied: protobuf in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (3.20.3) Requirement already satisfied: sympy in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (1.11.1) Requirement already satisfied: humanfriendly>=9.1 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from coloredlogs->onnxruntime-gpu) (10.0) Requirement already satisfied: mpmath>=0.19 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from sympy->onnxruntime-gpu) (1.3.0) Downloading onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121.6 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 16.8 MB/s eta 0:00:00 Installing collected packages: onnxruntime-gpu Successfully installed onnxruntime-gpu-1.15.1
```

and then pip show onnxruntime-gpu gives me:
```bash
Name: onnxruntime-gpu Version: 1.15.1 Summary: ONNX Runtime is a runtime accelerator for Machine Learning models Home-page: https://onnxruntime.ai Author: Microsoft Corporation Author-email: onnxruntime@microsoft.com License: MIT License Location: /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy Required-by: 
```

### Version?

i am using this [version](https://github.com/microsoft/Olive/commit/a65b453ba7d15d5b811281c6facb11a9fcc65ec3) from main

**Comment by jsoto-gladia** [comment]
ok thanks. Let me try it

**Comment by jsoto-gladia** [comment]
i have run the following commands:
```
python -m pip uninstall -y onnxruntime ort-nightly onnxruntime-gpu ort-nightly-gpu
python -m pip install ort-nightly-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

I end up with the following packages installed : 
`pip freeze | grep onnx`

```
onnx==1.14.0
onnxruntime-extensions==0.8.0
```

`pip freeze | grep ort`

```
importlib-resources==6.0.1
ort-nightly-gpu==1.16.0.dev20230912006
```

running `python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual`works fine
I DO NOT run the command `python -m olive.workflows.run --config whisper_gpu_fp32.json --setup`
when I run `python -m olive.workflows.run --config whisper_gpu_fp32.json` I get it seems to work
when I run `python test_transcription.py --config whisper_gpu_fp32.json  ` I get the following error: 
```
models/conversion-transformers_optimization-insert_beam_search-prepost/whisper_gpu_fp32_gpu-cuda_model.json
{'type': 'ONNXModel', 'config': {'model_path': '/home/jsoto/code/Olive/examples/whisper/models/conversion-transformers_optimization-insert_beam_search-prepost/whisper_gpu_fp32_gpu-cuda_model.onnx', 'onnx_file_name': None, 'inference_settings': None, 'use_ort_extensions': True, 'hf_config': {'model_name': 'openai/whisper-tiny', 'task': None, 'feature': None, 'model_class': 'WhisperForConditionalGeneration', 'components': [{'name': 'encoder_decoder_init', 'io_config': 'get_encdec_io_config', 'component_func': 'get_encoder_decoder_init', 'dummy_inputs_func': 'encoder_decoder_init_dummy_inputs'}, {'name': 'decoder', 'io_config': 'get_dec_io_config', 'component_func': 'get_decoder', 'dummy_inputs_func': 'decoder_dummy_inputs'}], 'dataset': None, 'model_loading_args': None}}}
[2023-09-13 20:57:16,389] [WARNING] [__init__.py:203:_is_valid_ep] Error: [ONNXRuntimeError] : 1 : FAIL : subgraph_whisper_encoder.cc:43 Validate expect 2 inputs, got:3Olive will ignore this CPUExecutionProvider.Please make sure the environment with CPUExecutionProvider has the required dependencies.
Traceback (most recent call last):
  File "/home/jsoto/code/Olive/examples/whisper/test_transcription.py", line 117, in <module>
    output_text = main()
  File "/home/jsoto/code/Olive/examples/whisper/test_transcription.py", line 102, in main
    session = olive_model.prepare_session(None, "cpu")
  File "/home/jsoto/.pyenv/versions/olive-ii/lib/python3.9/site-packages/olive/model/__init__.py", line 338, in prepare_session
    return get_ort_inference_session(self.model_path, inference_settings, self.use_ort_extensions)
  File "/home/jsoto/.pyenv/versions/olive-ii/lib/python3.9/site-packages/olive/common/ort_inference.py", line 64, in get_ort_inference_session
    sess = ort.InferenceSession(
  File "/home/jsoto/.pyenv/versions/olive-ii/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jsoto/.pyenv/versions/olive-ii/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 471, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
```

**Comment by jambayk** [comment]
Looks like the workflow used some previously cached run which does not match the current version of ort. 

Can you run the workflow again after deleting the `cache` subdirectory? 
Also, there is a bug in the latest ort-nightly. so please install this version
`pip install ort-nightly-gpu==1.16.0.dev20230903001 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/`

**Comment by jsoto-gladia** [comment]
yes that worked. The following procedure makes everything work for me:
```bash
cd examples/whisper
pip install -r requirements.txt
python -m pip uninstall -y onnxruntime ort-nightly onnxruntime-gpu ort-nightly-gpu
pip install ort-nightly-gpu==1.16.0.dev20230903001 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

```bash
pip freeze | grep onnx
pip freeze | grep ort
```

```bash
onnx==1.14.0
onnxruntime-extensions==0.8.0
importlib-resources==6.0.1
ort-nightly-gpu==1.16.0.dev20230903001
```


```bash
python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual
python -m olive.workflows.run --config whisper_gpu_fp32.json 
python test_transcription.py --config whisper_gpu_fp32.json 
```

**Comment by jsoto-gladia** [comment]
Thanks for the help
