### ISSUE TITLE
[Bug]: No model is selected. Skip packaging output artifacts. whisper

### ISSUE THREAD

**Issue by jsoto-gladia** [microsoft/Olive#575]
### What happened?

I followed the procedure on a v100s but no model was built. Can you help me out ? 
the procedure: 
```bash
pyenv install 3.9
pyenv virtualenv 3.9 olive
pyenv shell olive
```

```bash
cd Olive
python -m pip install .
cd examples/whisper
pip install -r requirements.txt
python -m pip uninstall -y onnxruntime ort-nightly onnxruntime-gpu ort-nightly-gpu
pip install ort-nightly-gpu==1.16.0.dev20230903001 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

```bash
python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual
python -m olive.workflows.run --config whisper_gpu_fp32.json --setup
python -m olive.workflows.run --config whisper_gpu_fp32.json 
```

However the last command issues no model with the following logs:
`
(olive) jsoto@moon:~/code/rd/Olive/examples/whisper$ python -m olive.workflows.run --config whisper_gpu_fp32.json --setup
[2023-09-17 17:57:56,615] [INFO] [run.py:114:dependency_setup] The following packages are required in the local environment: ['onnxruntime-gpu']
[2023-09-17 17:57:56,656] [INFO] [run.py:219:check_local_ort_installation] ort-nightly-gpu is already installed.
(olive) jsoto@moon:~/code/rd/Olive/examples/whisper$ python -m olive.workflows.run --config whisper_gpu_fp32.json 
[2023-09-17 17:58:00,967] [DEBUG] [engine.py:704:resolve_goals] Resolving goals: {'latency': {'avg': None}}
[2023-09-17 17:58:00,967] [DEBUG] [engine.py:723:resolve_goals] No baseline got as no goal is provided the the goal is threshold
[2023-09-17 17:58:00,968] [DEBUG] [engine.py:488:run_no_search] Step no search with search point {'OnnxConversion': {}, 'OrtTransformersOptimization': {}, 'InsertBeamSearch': {}, 'AppendPrePostProcessingOps': {}} ...
[2023-09-17 17:58:00,968] [INFO] [engine.py:966:_run_pass] Running pass OnnxConversion
[2023-09-17 17:58:00,968] [DEBUG] [engine.py:985:_run_pass] Loading model from cache ...
[2023-09-17 17:58:00,973] [INFO] [engine.py:966:_run_pass] Running pass OrtTransformersOptimization
[2023-09-17 17:58:00,973] [DEBUG] [engine.py:985:_run_pass] Loading model from cache ...
[2023-09-17 17:58:00,978] [INFO] [engine.py:966:_run_pass] Running pass InsertBeamSearch
[2023-09-17 17:58:00,978] [DEBUG] [engine.py:985:_run_pass] Loading model from cache ...
[2023-09-17 17:58:00,980] [INFO] [engine.py:966:_run_pass] Running pass AppendPrePostProcessingOps
[2023-09-17 17:58:00,981] [DEBUG] [engine.py:985:_run_pass] Loading model from cache ...
[2023-09-17 17:58:00,982] [DEBUG] [engine.py:1115:_evaluate_model] Evaluating model ...
[2023-09-17 17:58:00,982] [DEBUG] [resource_path.py:151:create_resource_path] Resource path /home/jsoto/code/rd/Olive/examples/whisper/cache/models/3_AppendPrePostProcessingOps-2-3097f103eaceec737176902e94f7fc77/output_model/model.onnx is inferred to be of type file.
[2023-09-17 17:58:00,984] [DEBUG] [resource_path.py:151:create_resource_path] Resource path /home/jsoto/code/rd/Olive/examples/whisper/cache/models/3_AppendPrePostProcessingOps-2-3097f103eaceec737176902e94f7fc77/output_model/model.onnx is inferred to be of type file.
[2023-09-17 17:58:01,273] [DEBUG] [olive_evaluator.py:195:generate_metric_user_config_with_model_io] Model input shapes are not static. Cannot use inferred input shapes for creating dummy data. This will cause an error when creating dummy data for tuning.
[2023-09-17 17:58:01,288] [DEBUG] [resource_path.py:151:create_resource_path] Resource path /home/jsoto/code/rd/Olive/examples/whisper/data is inferred to be of type folder.
[2023-09-17 17:58:02,797] [WARNING] [engine.py:389:run] Failed to run Olive on gpu-cuda: The onnxruntime fallback happens. CUDAExecutionProvider is not in the session providers ['CPUExecutionProvider']. session._enable_fallback = True
Traceback (most recent call last):
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/engine/engine.py", line 362, in run
    output, model_ids = self.run_no_search(
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/engine/engine.py", line 495, in run_no_search
    ) = self._run_passes(next_step["passes"], model_config, model_id, data_root, accelerator_spec)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/engine/engine.py", line 943, in _run_passes
    signal = self._evaluate_model(model_config, model_id, data_root, evaluator_config, accelerator_spec)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/engine/engine.py", line 1141, in _evaluate_model
    signal = self.target.evaluate_model(model_config, data_root, metrics, accelerator_spec)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/systems/local.py", line 51, in evaluate_model
    return evaluator.evaluate(model, data_root, metrics, device=device, execution_providers=execution_providers)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 170, in evaluate
    metrics_res[metric.name] = self._evaluate_latency(
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 639, in _evaluate_latency
    return self._evaluate_onnx_latency(model, metric, dataloader, post_func, device, execution_providers)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 395, in _evaluate_onnx_latency
    OnnxEvaluator.disable_ort_fallback(session, execution_providers)
  File "/home/jsoto/.pyenv/versions/olive/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 655, in disable_ort_fallback
    raise OliveEvaluationException(
olive.exception.OliveEvaluationException: The onnxruntime fallback happens. CUDAExecutionProvider is not in the session providers ['CPUExecutionProvider']. session._enable_fallback = True
[2023-09-17 17:58:02,817] [INFO] [engine.py:392:run] Run history for gpu-cuda:
[2023-09-17 17:58:02,823] [INFO] [engine.py:646:dump_run_history] run history:
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| model_id                                                                           | parent_model_id                                                                    | from_pass                   |   duration_sec | metrics   |
+====================================================================================+====================================================================================+=============================+================+===========+
| 642633f35ec0ddd526cfbc29c8201229                                                   |                                                                                    |                             |                |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 0_OnnxConversion-642633f35ec0ddd526cfbc29c8201229-876fd35e5c293d58a2c5273b55dd9113 | 642633f35ec0ddd526cfbc29c8201229                                                   | OnnxConversion              |       12.1649  |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 1_OrtTransformersOptimization-0-25f62cdf1460731b2a57305fd9a99b88                   | 0_OnnxConversion-642633f35ec0ddd526cfbc29c8201229-876fd35e5c293d58a2c5273b55dd9113 | OrtTransformersOptimization |        7.45471 |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 2_InsertBeamSearch-1-c52f3e3227042bddb2aeb3bdc2840a44                              | 1_OrtTransformersOptimization-0-25f62cdf1460731b2a57305fd9a99b88                   | InsertBeamSearch            |        5.46747 |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 3_AppendPrePostProcessingOps-2-3097f103eaceec737176902e94f7fc77                    | 2_InsertBeamSearch-1-c52f3e3227042bddb2aeb3bdc2840a44                              | AppendPrePostProcessingOps  |        4.95926 |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
[2023-09-17 17:58:02,823] [INFO] [engine.py:397:run] Package top ranked 0 models as artifacts
[2023-09-17 17:58:02,824] [WARNING] [packaging_generator.py:35:generate_output_artifacts] No model is selected. Skip packaging output artifacts.
`

### Version?

main

**Comment by guotuofeng** [comment]
would you please help double check the available EPs? from the logging, it seems the cuda EP is not available.

**Comment by jsoto-gladia** [comment]
hello how can I check that knowing that the following is the result of nvidia-smi ?

Mon Sep 18 05:50:27 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100S-PCIE-32GB          Off | 00000000:00:06.0 Off |                    0 |
| N/A   31C    P0              26W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |

**Comment by guotuofeng** [comment]
Just run onnxruntime.get_available_providers would return the available providers.

**Comment by jsoto-gladia** [comment]
how strange....
>>> onnxruntime.get_available_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']

**Comment by jsoto-gladia** [comment]
and the result of  pip freeze | grep onnx && pip freeze | grep ort is
onnx==1.14.0
onnxruntime-extensions==0.8.0
importlib-resources==6.0.1
ort-nightly-gpu==1.16.0.dev20230903001

**Comment by guotuofeng** [comment]
@jsoto-gladia, would you please use a local onnx model to try the CUDA EP like:

session = onnxruntime.InferenceSession(
        model, providers=['CUDAExecutionProvider', 'CPUExecutionProvider']
)
print(session.get_providers())

From the current log, it seems the output only contains CPU EP. If this is the case, some of the cuda EP setting is not correct configured.

**Comment by trajepl** [comment]
Follow above setup procedure, whisper case worked well for me.

Just ensure the code snippet that Mike provide can work with CUDA EP.

**Comment by jsoto-gladia** [comment]
re installing everything solved the issue. Thanks for the support
