### ISSUE TITLE
model_type field required (type=value_error.missing)

### ISSUE THREAD

**Issue by hemant-gharat** [microsoft/Olive#628]
Can somebody explain to me the cause of and solution for the following error?
I'm getting the below error when I run this command.
python -m olive.workflows.run --config whisper_cpu_int8.json

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\__main__.py", line 17, in <module>
    run(**vars(args))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\run.py", line 176, in run
    best_execution = engine.run(
                     ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 327, in run
    self.setup_passes(accelerator_spec)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 402, in setup_passes
    pass_cfg = pass_cls.generate_search_space(accelerator_spec, pass_cfg, config["disable_search"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\passes\olive_pass.py", line 130, in generate_search_space
    config = validate_config(config, PassConfigBase, config_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\common\config_utils.py", line 266, in validate_config
    config = instance_class(**config)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OrtTransformersOptimizationConfig
model_type
  field required (type=value_error.missing)

**Comment by xiaoyu-work** [comment]
Hi @hemant-gharat , can you try to run Whisper example with Olive latest main branch?

**Comment by hemant-gharat** [comment]
> Hi @hemant-gharat , can you try to run Whisper example with Olive latest main branch?

Hi @xiaoyu-work, I appreciate your response.

Yes, I tried using the Olive latest main branch to execute the whisper example.
Still, I'm getting the same error. Please look at the below

From https://github.com/microsoft/Olive
 * branch            main       -> FETCH_HEAD
Already up to date.

PS C:\Users\admin\Documents\olive-mic\Olive\examples\whisper> python prepare_whisper_configs.py --model_name openai/whisper-tiny.en --no_audio_decoder

PS C:\Users\admin\Documents\olive-mic\Olive\examples\whisper> python -m olive.workflows.run --config whisper_cpu_int8.json --setup
[2023-10-06 11:58:28,415] [INFO] [run.py:111:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-10-06 11:58:28,416] [INFO] [run.py:115:dependency_setup] onnxruntime is already installed.

PS C:\Users\admin\Documents\olive-mic\Olive\examples\whisper> python -m olive.workflows.run --config whisper_cpu_int8.json        
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\__main__.py", line 17, in <module>
    run(**vars(args))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\run.py", line 176, in run
    best_execution = engine.run(
                     ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 327, in run
    self.setup_passes(accelerator_spec)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 402, in setup_passes
    pass_cfg = pass_cls.generate_search_space(accelerator_spec, pass_cfg, config["disable_search"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\passes\olive_pass.py", line 130, in generate_search_space
    config = validate_config(config, PassConfigBase, config_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\common\config_utils.py", line 266, in validate_config
    config = instance_class(**config)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OrtTransformersOptimizationConfig
model_type
  field required (type=value_error.missing)

**Comment by hemant-gharat** [comment]
Hello @xiaoyu-work , I appreciate your help.
I followed your instructions, but I'm receiving the following issue: Can you help?

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/olive/engine/engine.py", line 993, in _run_pass
    output_model = host.run_pass(p, input_model, data_root, output_model_path, pass_search_point)
  File "/usr/local/lib/python3.10/dist-packages/olive/systems/local.py", line 33, in run_pass
    return the_pass.run(model, data_root, output_model_path, point)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/olive_pass.py", line 397, in run
    return self._run_for_config(model, data_root, config, output_model_path)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/onnx/append_pre_post_processing_ops.py", line 101, in _run_for_config
    add_ppp(model.load_model(), tmp_model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/utils/whisper_prepost.py", line 349, in add_pre_post_processing_to_model
    onnx.checker.check_model(output_filepath)
  File "/usr/local/lib/python3.10/dist-packages/onnx/checker.py", line 125, in check_model
    C.check_model_path(model, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
[2023-10-06 20:09:03,790] [WARNING] [engine.py:381:run] Failed to run Olive on cpu-cpu: Field 'shape' of 'type' is required but missing.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/olive/engine/engine.py", line 354, in run
    output, model_ids = self.run_no_search(
  File "/usr/local/lib/python3.10/dist-packages/olive/engine/engine.py", line 482, in run_no_search
    ) = self._run_passes(next_step["passes"], model, model_id, data_root, accelerator_spec)
  File "/usr/local/lib/python3.10/dist-packages/olive/engine/engine.py", line 902, in _run_passes
    model, model_id = self._run_pass(pass_id, pass_search_point, model, model_id, data_root, accelerator_spec)
  File "/usr/local/lib/python3.10/dist-packages/olive/engine/engine.py", line 993, in _run_pass
    output_model = host.run_pass(p, input_model, data_root, output_model_path, pass_search_point)
  File "/usr/local/lib/python3.10/dist-packages/olive/systems/local.py", line 33, in run_pass
    return the_pass.run(model, data_root, output_model_path, point)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/olive_pass.py", line 397, in run
    return self._run_for_config(model, data_root, config, output_model_path)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/onnx/append_pre_post_processing_ops.py", line 101, in _run_for_config
    add_ppp(model.load_model(), tmp_model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/olive/passes/utils/whisper_prepost.py", line 349, in add_pre_post_processing_to_model
    onnx.checker.check_model(output_filepath)
  File "/usr/local/lib/python3.10/dist-packages/onnx/checker.py", line 125, in check_model
    C.check_model_path(model, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
[2023-10-06 20:09:03,801] [INFO] [engine.py:384:run] Package top ranked 0 models as artifacts
[2023-10-06 20:09:03,801] [WARNING] [packaging_generator.py:35:generate_output_artifacts] No model is selected. Skip packaging output artifacts.

**Comment by xiaoyu-work** [comment]
@hemant-gharat which onnxruntime version you are using? Can you try latest stable version 1.16.0?

**Comment by hemant-gharat** [comment]
Hi @xiaoyu-work The problem was resolved by reinstalling everything. Thank you so much for your assistance.
