### ISSUE TITLE
[FR]: Enable optimization by onnxruntime on stable_diffusion.py

### ISSUE THREAD

**Issue by kazssym** [microsoft/Olive#645]
### Proposal Summary

The stable_diffusion.py script fails to detect GPU for optimization, showing the following message.

```
There is no gpu for onnxruntime to do optimization.
```

I hope the script will fully support optimization on DirectML as I have added a provider selection option to ONNX Runtime's optimizer for 1.17.0.

Update: The message is from here.
https://github.com/microsoft/onnxruntime/blob/2a1fd2586ff9ea7b2af94a7d4b1b3c124f5f3cda/onnxruntime/python/tools/transformers/optimizer.py#L93-L97

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [X] Passes
- [ ] Other

**Comment by xiaoyu-work** [comment]
Hi @kazssym , what is the onnxruntime version you are using? Is it [onnxruntime-directml](https://pypi.org/project/onnxruntime-directml/)?

**Comment by kazssym** [comment]
@xiaoyu-work, I saw the message with onnxruntime-directml 1.16.1. It did not use DirectML for basic optimization.

**Comment by kazssym** [comment]
I tried to pass a new parameter to ONNX Runtime on #651 but am still failing to run the optimization on DirectML.

**Comment by FrakerKill** [comment]
I have the same problem

**Comment by AshD** [comment]
I am seeing the same issue. Below is the version info

Collecting onnxruntime-directml
  Downloading onnxruntime_directml-1.16.2-cp310-cp310-win_amd64.whl (15.2 MB)

**Comment by vibbix** [comment]
Same issue here on my 6900XT. In fact, my GPU driver crash's entirely
[DxDiag.txt](https://github.com/microsoft/Olive/files/13444424/DxDiag.txt)
[Anaconda Prompt (miniconda3).txt](https://github.com/microsoft/Olive/files/13444425/Anaconda.Prompt.miniconda3.txt)

**Comment by emircanerkul** [comment]
Same in 6800xt

```
To create a public link, set `share=True` in `launch()`.
Startup time: 28.7s (prepare environment: 23.8s, import torch: 2.5s, import gradio: 1.2s, setup paths: 1.6s, initialize shared: 0.9s, other imports: 0.4s, load scripts: 1.0s, create ui: 0.6s, gradio launch: 0.3s).
loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\xxxxx\.conda\envs\Automatic1111_olive\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\xxxxx\.conda\envs\Automatic1111_olive\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\stable-diffusion-webui-directml\modules\ui.py", line 2975, in <lambda>
    visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit"
  File "G:\stable-diffusion-webui-directml\modules\shared_items.py", line 110, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "G:\stable-diffusion-webui-directml\modules\sd_models.py", line 544, in get_sd_model
    load_model()
  File "G:\stable-diffusion-webui-directml\modules\sd_models.py", line 631, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "G:\stable-diffusion-webui-directml\modules\sd_models.py", line 265, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file G:\stable-diffusion-webui-directml\model.ckpt
 - directory G:\stable-diffusion-webui-directml\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
Unloaded weights 0.0s.
model_index.json: 100%|███████████████████████████████████████████████████████████████████████| 541/541 [00:00<?, ?B/s]
safety_checker/config.json: 100%|█████████████████████████████████████████████████████████| 4.72k/4.72k [00:00<?, ?B/s]
text_encoder/config.json: 100%|███████████████████████████████████████████████████████████████| 617/617 [00:00<?, ?B/s]
(…)ature_extractor/preprocessor_config.json: 100%|████████████████████████████████████████████| 342/342 [00:00<?, ?B/s]
tokenizer/special_tokens_map.json: 100%|██████████████████████████████████████████████████████| 472/472 [00:00<?, ?B/s]
scheduler/scheduler_config.json: 100%|█████████████████████████████████████████████████| 308/308 [00:00<00:00, 308kB/s]
tokenizer/tokenizer_config.json: 100%|████████████████████████████████████████████████████████| 806/806 [00:00<?, ?B/s]
unet/config.json: 100%|███████████████████████████████████████████████████████████████████████| 743/743 [00:00<?, ?B/s]
tokenizer/merges.txt: 100%|█████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.00MB/s]
vae/config.json: 100%|████████████████████████████████████████████████████████████████████████| 547/547 [00:00<?, ?B/s]
tokenizer/vocab.json: 100%|███████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 1.63MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████| 335M/335M [01:27<00:00, 3.84MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████| 492M/492M [02:25<00:00, 3.38MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████| 1.22G/1.22G [04:06<00:00, 4.92MB/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████| 3.44G/3.44G [06:43<00:00, 8.52MB/s]
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████| 15/15 [06:45<00:00, 27.01s/it]
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00, 10.77it/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████| 3.44G/3.44G [06:43<00:00, 12.4MB/s]
Optimizing text_encoder
[2023-11-28 08:11:40,409] [INFO] [engine.py:179:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-11-28 08:11:40,430] [INFO] [engine.py:929:_run_pass] Running pass convert:OnnxConversion
G:\stable-diffusion-webui-directml\modules\dml\hijack\transformers.py:13: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  min = torch.tensor(torch.finfo(dtype).min, device="cpu")
G:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:287: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
G:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:295: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if causal_attention_mask.size() != (bsz, 1, tgt_len, src_len):
G:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:327: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
[2023-11-28 08:11:46,712] [INFO] [engine.py:929:_run_pass] Running pass optimize:OrtTransformersOptimization
[2023-11-28 08:11:46,977] [ERROR] [onnxruntime]-[optimizer.py:96:optimize_by_onnxruntime] There is no gpu for onnxruntime to do optimization.
ERROR:onnxruntime.transformers.optimizer:There is no gpu for onnxruntime to do optimization.
[2023-11-28 08:11:57,359] [INFO] [footprint.py:183:create_pareto_frontier] pareto frontier points: 1_OrtTransformersOptimization-0-0a001e25d2c23d8172228a97e9656768
{
  "latency-avg": 13.59194
}
[2023-11-28 08:11:57,360] [INFO] [engine.py:610:create_pareto_frontier_footprints] Output all 1 models
[2023-11-28 08:11:57,361] [INFO] [engine.py:357:run] Run history for gpu-dml:
[2023-11-28 08:11:57,362] [INFO] [engine.py:636:dump_run_history] Please install tabulate for better run history output
[2023-11-28 08:11:57,362] [INFO] [engine.py:372:run] No packaging config provided, skip packaging artifacts
Optimized text_encoder

Optimizing unet
[2023-11-28 08:11:57,380] [INFO] [engine.py:179:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-11-28 08:11:57,396] [INFO] [engine.py:929:_run_pass] Running pass convert:OnnxConversion
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:878: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if dim % default_overall_up_factor != 0:
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\resnet.py:260: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\resnet.py:266: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\resnet.py:168: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\resnet.py:181: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if hidden_states.shape[0] >= 64:
G:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:1160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not return_dict:
[2023-11-28 08:13:11,424] [INFO] [engine.py:929:_run_pass] Running pass optimize:OrtTransformersOptimization
[2023-11-28 08:13:11,479] [ERROR] [onnxruntime]-[optimizer.py:96:optimize_by_onnxruntime] There is no gpu for onnxruntime to do optimization.
[2023-11-28 08:13:11,479] [ERROR] [onnxruntime]-[optimizer.py:96:optimize_by_onnxruntime] There is no gpu for onnxruntime to do optimization.
ERROR:onnxruntime.transformers.optimizer:There is no gpu for onnxruntime to do optimization.

```

**Comment by gurwinderintel** [comment]
Getting this same error while optimizing models on Intel Arc 770 and my driver version is 32.0.101.9999, Although optimized model fully uses GPU (Usage 90%+).

**Comment by guotuofeng** [comment]
PR https://github.com/microsoft/Olive/pull/878/ should fix the bug.  

Could you guys try the branch with the ort-nightly-directml?
