### ISSUE TITLE
[Bug]: ImportError: cannot import name 'load_model' from ' 6800xt model

### ISSUE THREAD

**Issue by dungeun** [microsoft/Olive#652]
### What happened?

(olive) C:\Users\admin\olive\examples\directml\stable_diffusion>python stable_diffusion.py --optimize
Traceback (most recent call last):
  File "C:\Users\admin\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 18, in <module>
    from olive.workflows import run as olive_run
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\workflows\__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\workflows\run\run.py", line 16, in <module>
    from olive.passes import Pass
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\passes\__init__.py", line 6, in <module>
    from olive.passes.onnx import *  # noqa: F403
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\__init__.py", line 17, in <module>
    from olive.passes.onnx.vitis_ai_quantization import VitisAIQuantization
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai_quantization.py", line 18, in <module>
    from olive.passes.onnx.vitis_ai import quantize_static
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\__init__.py", line 10, in <module>
    from olive.passes.onnx.vitis_ai.quantize import quantize_static
  File "C:\Users\admin\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\quantize.py", line 15, in <module>
    from onnxruntime.quantization.quant_utils import QuantFormat, QuantizationMode, QuantType, load_model
ImportError: cannot import name 'load_model' from 'onnxruntime.quantization.quant_utils' (C:\Users\admin\miniconda3\envs\olive\lib\site-packages\onnxruntime\quantization\quant_utils.py)

(olive) C:\Users\admin\olive\examples\directml\stable_diffusion>

### Version?

https://community.amd.com/t5/ai/how-to-running-optimized-automatic1111-stable-diffusion-webui-on/ba-p/625585

error

**Comment by jambayk** [comment]
Looks like you are using olive installed from PyPI using `pip install olive-ai` but that release is not in sync with main. 

To use the latest version of Olive, please install it from source using:
`python -m pip install pip install git+https://github.com/microsoft/Olive`
or run
`python -m pip install .` at the root of the Olive directory. 

Please refer to Olive installation for examples in [this readme](https://github.com/microsoft/Olive/blob/main/examples/README.md)
