### ISSUE TITLE
CUDAExecutionProvider is not in the session providers

### ISSUE THREAD

**Issue by its-tail08** [microsoft/Olive#656]
The following command with the CPU operates flawlessly when I run it.
python -m olive.workflows.run --config whisper_cpu_int8.json

however, I get an error when I use the below command to do the same with the GPU.
python -m olive.workflows.run --config whisper_gpu_int8.json

Versions -

Python 3.9.16
onnxruntime-gpu==1.16.1
GPU - Tesla T4

[2023-10-18 11:31:35,649] [WARNING] [engine.py:432:run_accelerator] Failed to run Olive on gpu-cuda: The onnxruntime fallback happens. CUDAExecutionProvider is not in the session providers ['CPUExecutionProvider']. session._enable_fallback = True
Traceback (most recent call last):
  File "/var/whisper/Olive-main/olive/engine/engine.py", line 412, in run_accelerator
    return self.run_no_search(
  File "/var/whisper/Olive-main/olive/engine/engine.py", line 483, in run_no_search
    should_prune, signal, model_ids = self._run_passes(
  File "/var/whisper/Olive-main/olive/engine/engine.py", line 903, in _run_passes
    signal = self._evaluate_model(model_config, model_id, data_root, evaluator_config, accelerator_spec)
  File "/var/whisper/Olive-main/olive/engine/engine.py", line 1090, in _evaluate_model
    signal = self.target.evaluate_model(model_config, data_root, metrics, accelerator_spec)
  File "/var/whisper/Olive-main/olive/systems/local.py", line 47, in evaluate_model
    return evaluator.evaluate(model, data_root, metrics, device=device, execution_providers=execution_providers)
  File "/var/whisper/Olive-main/olive/evaluator/olive_evaluator.py", line 173, in evaluate
    metrics_res[metric.name] = self._evaluate_latency(
  File "/var/whisper/Olive-main/olive/evaluator/olive_evaluator.py", line 635, in _evaluate_latency
    return self._evaluate_onnx_latency(model, metric, dataloader, post_func, device, execution_providers)
  File "/var/whisper/Olive-main/olive/evaluator/olive_evaluator.py", line 391, in _evaluate_onnx_latency
    OnnxEvaluator.disable_ort_fallback(session, execution_providers)
  File "/var/whisper/Olive-main/olive/evaluator/olive_evaluator.py", line 651, in disable_ort_fallback
    raise OliveEvaluationError(
olive.exception.OliveEvaluationError: The onnxruntime fallback happens. CUDAExecutionProvider is not in the session providers ['CPUExecutionProvider']. session._enable_fallback = True
[2023-10-18 11:31:35,665] [INFO] [engine.py:357:run] Run history for gpu-cuda:
[2023-10-18 11:31:35,670] [INFO] [engine.py:630:dump_run_history] run history:
.
.
.
.
Could you please let me know if there is something I'm missing?

**Comment by jambayk** [comment]
onnxruntime release their cpu and gpu packages separately. If you would like to use the cuda EP, please uninstall all existing onnxruntime installations and install onnxruntime-gpu. 
```
python -m pip uninstall -y onnxruntime ort-nightly
python -m pip install onnxruntime-gpu
```

Note: You can still use cpu EP with the gpu package.

**Comment by jambayk** [comment]
The commands can also be auto generated for you by Olive if you run 

`python -m olive.workflows.run --config whisper_gpu_int8.json --setup` 

It checks you current python environment for workflow dependencies.

**Comment by its-tail08** [comment]
Hello @jambayk ,Thanks for reply.
The problem has been fixed; the library path was the cause of the problem.
