### ISSUE TITLE
[Bug]: During Inference with ORTStableDiffusionXLPipeline - [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for GroupNorm(1) node with name 'GroupNorm_22'

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#733]
### What happened?

1. Converted the SDXL model using Olive toolset and uploaded to https://huggingface.co/softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx
2. No errors when generating the Olive version of the model from **stabilityai/stable-diffusion-xl-base-1.0**
3. Ran the following code to test the model
```
from optimum.onnxruntime import ORTStableDiffusionXLPipeline

model_id="softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx"
pipeline = ORTStableDiffusionXLPipeline.from_pretrained(model_id)
prompt = "sailing ship in storm by Leonardo da Vinci"
image = pipeline(prompt).images[0]
```
Error stack:
 File "C:\AI\research\olive\olive\examples\directml\stable_diffusion_xl\TestSDXL.py", line 6, in <module>
    pipeline = ORTStableDiffusionXLPipeline.from_pretrained(model_id)
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 622, in from_pretrained
    return super().from_pretrained(
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_diffusion.py", line 336, in _from_pretrained
    vae_decoder, text_encoder, unet, vae_encoder, text_encoder_2 = cls.load_model(
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_diffusion.py", line 213, in load_model
    vae_decoder = ORTModel.load_model(vae_decoder_path, provider, session_options, provider_options)
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 369, in load_model
    return ort.InferenceSession(
  File "C:\AI\research\olive\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\AI\research\olive\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
**onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for GroupNorm(1) node with name 'GroupNorm_22'**

### Version?

Latest Master branch

**Comment by jambayk** [comment]
Was you olive package installed from source or using `pip install olive-ai`? 
If it's the later, what version is it? I had this PR https://github.com/microsoft/Olive/pull/674 after version 0.3.3 which made some configs regarding group norm incompatible with it. 

looking at the error, looks like the groupnorm node's input is fp32 (1) and not fp16. Which makes me think your version of olive is outdated and it is not picking up the `force_fp16_inputs` config properly.

If you have the latest olive (0.4.0) or build it from the main branch, can you make sure you have the latest version of onnxruntime-directml (1.16.2)?

**Comment by jambayk** [comment]
Please try it again with the execution provider like in https://github.com/microsoft/Olive/blob/main/examples/directml/stable_diffusion_xl/stable_diffusion_xl.py#L223
It's probably using the CPU execution provider which doesn't not support the op.

**Comment by AshD** [comment]
Thanks @Jambayk 

Here is the updated code. The config was returning empty and when I set it, the CPU went to 90% during Image Gen and then failed. I have a Core i9 13th Gen/RTX 4090/128GB memory. See output below.

```
from optimum.onnxruntime import ORTStableDiffusionXLPipeline

model_id="softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx"
pipeline = ORTStableDiffusionXLPipeline.from_pretrained(model_id, provider="DmlExecutionProvider")
prompt = "sailing ship in storm by Leonardo da Vinci"

# Debugging: Print the configuration
print("UNet Config:", pipeline.unet.config)
# Manually setting the default configuration
default_config = {
    "sample_size": 1024,  
}
pipeline.unet.config = default_config

image = pipeline(prompt).images[0]
```

Fetching 17 files: 100%|███████████████████████████████████████████████████████████████████████| 17/17 [00:00<?, ?it/s]
2023-11-19 08:00:03.0326682 [W:onnxruntime:, session_state.cc:1162 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 08:00:03.0365148 [W:onnxruntime:, session_state.cc:1164 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-11-19 08:00:03.8914675 [W:onnxruntime:, session_state.cc:1162 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 08:00:03.8951344 [W:onnxruntime:, session_state.cc:1164 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-11-19 08:00:07.2085572 [W:onnxruntime:, session_state.cc:1162 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 08:00:07.2123651 [W:onnxruntime:, session_state.cc:1164 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-11-19 08:00:07.9031403 [W:onnxruntime:, session_state.cc:1162 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 08:00:07.9069786 [W:onnxruntime:, session_state.cc:1164 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-11-19 08:00:11.2793714 [W:onnxruntime:, session_state.cc:1162 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 08:00:11.2830900 [W:onnxruntime:, session_state.cc:1164 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
UNet Config: {}
  2%|█▌                                                                              | 1/50 [01:41<1:22:43, 101.29s/it]
Traceback (most recent call last):
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion_xl\TestSDXL.py", line 21, in <module>
    image = pipeline(prompt).images[0]
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\pipelines\diffusers\pipeline_stable_diffusion_xl.py", line 452, in __call__
    noise_pred = self.unet(
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_diffusion.py", line 482, in __call__
    return self.forward(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\optimum\onnxruntime\modeling_diffusion.py", line 519, in forward
    outputs = self.session.run(None, onnx_inputs)
  File "C:\AI\research\olive\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(897)\onnxruntime_pybind11_state.pyd!00007FFDA30349F2: (caller: 00007FFDA30353E6) Exception(2) tid(3e98) 887A0006 The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application.

**Comment by AshD** [comment]
Also, here is a list of my PIP packages. I got the latest Olive using git clone https://github.com/microsoft/olive

```
(.venv) C:\AI\research\olive\olive\examples\directml\stable_diffusion_xl>pip list
Package                Version
---------------------- ------------
accelerate             0.24.1
aiohttp                3.9.0
aiosignal              1.3.1
alembic                1.12.1
antlr4-python3-runtime 4.9.3
async-timeout          4.0.3
attrs                  23.1.0
certifi                2022.12.7
charset-normalizer     2.1.1
colorama               0.4.6
coloredlogs            15.0.1
colorlog               6.7.0
datasets               2.15.0
diffusers              0.23.1
dill                   0.3.7
evaluate               0.4.1
filelock               3.9.0
flatbuffers            23.5.26
frozenlist             1.4.0
fsspec                 2023.10.0
greenlet               3.0.1
huggingface-hub        0.19.4
humanfriendly          10.0
idna                   3.4
importlib-metadata     6.8.0
invisible-watermark    0.2.0
Jinja2                 3.1.2
Mako                   1.3.0
MarkupSafe             2.1.3
mpmath                 1.3.0
multidict              6.0.4
multiprocess           0.70.15
networkx               3.0
numpy                  1.24.1
olive-ai               0.4.0
omegaconf              2.3.0
onnx                   1.15.0
onnxruntime-directml   1.16.2
onnxruntime-extensions 0.9.0
opencv-python          4.8.1.78
optimum                1.14.1
optuna                 3.4.0
packaging              23.2
pandas                 2.1.3
Pillow                 9.3.0
pip                    23.3.1
protobuf               3.20.3
psutil                 5.9.6
pyarrow                14.0.1
pyarrow-hotfix         0.5
pydantic               1.10.13
pyreadline3            3.4.1
python-dateutil        2.8.2
pytz                   2023.3.post1
PyWavelets             1.5.0
PyYAML                 6.0.1
regex                  2023.10.3
requests               2.28.1
responses              0.18.0
safetensors            0.4.0
scipy                  1.11.4
sentencepiece          0.1.99
setuptools             65.5.0
six                    1.16.0
SQLAlchemy             2.0.23
sympy                  1.12
tabulate               0.9.0
tokenizers             0.15.0
torch                  2.1.1+cu118
torchaudio             2.1.1+cu118
torchmetrics           0.10.3
torchvision            0.16.1+cu118
tqdm                   4.66.1
transformers           4.35.2
typing_extensions      4.4.0
tzdata                 2023.3
urllib3                1.26.13
xxhash                 3.4.1
yarl                   1.9.2
zipp                   3.17.0
```

**Comment by jambayk** [comment]
I am not familiar with this error message from the DML EP. But @PatriceVignola might have better insights?

**Comment by PatriceVignola** [comment]
Hey @AshD,

The sample size should be the size of the image that you want to generate divided by `8`. So here, it should be `128` instead of `1024`. Also, for better performance, I suggest overriding the dynamic dimensions. Here's a working snippet that should get you started:

```python
import onnxruntime
from optimum.onnxruntime import ORTStableDiffusionXLPipeline

batch_size = 1
image_size = 1024

sess_options = onnxruntime.SessionOptions()
sess_options.add_free_dimension_override_by_name("unet_sample_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_sample_channels", 4)
sess_options.add_free_dimension_override_by_name("unet_sample_height", image_size // 8)
sess_options.add_free_dimension_override_by_name("unet_sample_width", image_size // 8)
sess_options.add_free_dimension_override_by_name("unet_time_batch", 1)
sess_options.add_free_dimension_override_by_name("unet_hidden_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_hidden_sequence", 77)
sess_options.add_free_dimension_override_by_name("unet_text_embeds_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_text_embeds_size", 1280)
sess_options.add_free_dimension_override_by_name("unet_time_ids_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_time_ids_size", 6)

model_id="softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx"
pipeline = ORTStableDiffusionXLPipeline.from_pretrained(model_id, provider="DmlExecutionProvider", session_options=sess_options)
prompt = "sailing ship in storm by Leonardo da Vinci"

# Debugging: Print the configuration
print("UNet Config:", pipeline.unet.config)
# Manually setting the default configuration
default_config = {
    "sample_size": image_size // 8,
}
pipeline.unet.config = default_config

image = pipeline(prompt).images[0]
```

**Comment by AshD** [comment]
Thanks @PatriceVignola. That worked for a batch size of 1 :-)

For a batch size of 8, I got this error 
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: encoder_hidden_states for the following indices
 index: 0 Got: 2 Expected: 16

**Comment by PatriceVignola** [comment]
@AshD To generate more than 1 image for a single prompt, replace the last line with the following one:

`image = pipeline(prompt, num_images_per_prompt=batch_size).images[0]`

**Comment by AshD** [comment]
Thanks @PatriceVignola. That worked :-)

Closing this issue. Thanks again for your and @jambayk help
