### ISSUE TITLE
[Bug]: MIT/ast-finetuned-speech-commands-v2 leads to KeyError in evaluation?

### ISSUE THREAD

**Issue by vymao** [microsoft/Olive#735]
### What happened?

I am trying to use Olive to optimize `MIT/ast-finetuned-speech-commands-v2 ` after success with the Whisper example provided. My setup json is currently: 

```
{
    "input_model":{
        "type": "PyTorchModel",
        "config": {
            "hf_config": {
                "model_class": "ASTForAudioClassification",
                "model_name": "MIT/ast-finetuned-speech-commands-v2",
                "task": "audio-classification",
                "dataset": {
                    "data_name":"speech_commands",
                    "subset": "v0.02",
                    "split": "validation",
                    "input_cols": ["audio"],
                    "label_cols": ["label"],
                    "batch_size": 1
                }
            }
        }
    },
    "evaluators": {
        "common_evaluator": {
            "metrics":[
                {
                    "name": "accuracy",
                    "type": "accuracy",
                    "backend": "huggingface_metrics",
                    "sub_types": [
                        {"name": "accuracy", "priority": 1, "goal": {"type": "max-degradation", "value": 0.05}},
                        {"name": "f1"}
                    ]
                },
                {
                    "name": "latency",
                    "type": "latency",
                    "sub_types": [
                        {"name": "avg", "priority": 2, "goal": {"type": "percent-min-improvement", "value": 5}},
                        {"name": "max"},
                        {"name": "min"}
                    ]
                }
            ]
        }
    },
    "passes": {
        "conversion": {
            "type": "OnnxConversion",
            "config": {
                "target_opset": 13
            }
        },
        "transformers_optimization": {
            "type": "OrtTransformersOptimization",
            "disable_search": true
        },
        "quantization": {
            "type": "OnnxQuantization",
            "config": {
                "quant_preprocess": true,
                "per_channel": false,
                "reduce_range": false,
                "calibrate_method": "MinMax",
                "data_config": "__input_model_data_config__"
            }
        },
        "perf_tuning": {
            "type": "OrtPerfTuning",
            "config": {
                "data_config": "__input_model_data_config__"
            }
        }
    },
    "engine": {
        "search_strategy": {
            "execution_order": "joint",
            "search_algorithm": "tpe",
            "search_algorithm_config": {
                "num_samples": 3,
                "seed": 0
            }
        },
        "evaluator": "common_evaluator",
        "execution_providers": ["CPUExecutionProvider", "OpenVINOExecutionProvider"],
        "cache_dir": "cache",
        "output_dir" : "models/ast_cpu"
    }
}
```

However, this leads to an error like: 
```
Traceback (most recent call last):
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/engine/engine.py", line 398, in run_accelerator
    results = self._evaluate_model(
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/engine/engine.py", line 1090, in _evaluate_model
    signal = self.target.evaluate_model(model_config, data_root, metrics, accelerator_spec)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/systems/local.py", line 47, in evaluate_model
    return evaluator.evaluate(model, data_root, metrics, device=device, execution_providers=execution_providers)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 166, in evaluate
    dataloader, eval_func, post_func = OliveEvaluator.get_user_config(model.framework, data_root, metric)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/evaluator/olive_evaluator.py", line 245, in get_user_config
    dataloader = dataloader or dc.create_dataloader(data_root)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/data/container/data_container.py", line 61, in create_dataloader
    pre_process_dataset = self.pre_process(dataset)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/data/container/data_container.py", line 45, in pre_process
    return self.config.pre_process(dataset, **self.config.pre_process_params)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/data/component/pre_process_data.py", line 96, in huggingface_pre_process
    tokenized_datasets = _huggingface_pre_process_helper(
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/data/component/pre_process_data.py", line 47, in _huggingface_pre_process_helper
    tokenized_datasets = dataset.map(
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3474, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/olive/data/component/pre_process_data.py", line 74, in _tokenizer_and_align_labels
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 752, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/Users/victor/anaconda3/envs/transformers-v2/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 745, in __getitem__
    raise KeyError(key)
KeyError: <class 'transformers.models.audio_spectrogram_transformer.configuration_audio_spectrogram_transformer.ASTConfig'>
[2023-11-19 20:18:04,025] [INFO] [engine.py:357:run] Run history for cpu-cpu:
[2023-11-19 20:18:04,026] [INFO] [engine.py:632:dump_run_history] Please install tabulate for better run history output
[2023-11-19 20:18:04,026] [INFO] [engine.py:372:run] No packaging config provided, skip packaging artifacts
(transformers-v2) victor@Victors-MBP python % 
```

I'm not 100% of the root cause here. Are HuggingFace audio models not directly supported against Audio datasets right now? I noticed in the Whisper example that, while the model was downloaded from HuggingFace, the actual dataset for evaluation was not. Presumably, one would want the feature extractor (not the tokenizer) for audio models?

### Version?

0.3.3

**Comment by trajepl** [comment]
Yes, the task is `audio-classification` which is not supported as of now. We mainly cover the case for text related tasks like  
 generation or classification.
 
Will try to investigate the AST case and add the support in data configs.

Before this, you can write the customized user scripts to load you data like what we did for whisper.

**Comment by trajepl** [comment]
https://microsoft.github.io/Olive/tutorials/configure_data.html#how-to-configure-data
Besides, as you mentioned, the feature extractor might be the right step for audio models in pre-process part. You can also customize it in data configs. More details: https://microsoft.github.io/Olive/tutorials/configure_data.html#how-to-configure-data

**Comment by trajepl** [comment]
@vymao Feel free to try this PR
https://github.com/microsoft/Olive/pull/762
![image](https://github.com/microsoft/Olive/assets/13343117/a3a5e6e4-e7b3-4e08-b34c-298744ec4687)

**Comment by trajepl** [comment]
Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
We have 40 cpu to run actually. 😅 And the `perf_tuning` will try to search the config for better performance which may run model with multi-threads.

**Comment by jambayk** [comment]
Closing issue since support was added in linked issue.
Please reopen if it still exists for you.
