### ISSUE TITLE
[Bug]: whisper-medium process convertation finished with "Failed to run Olive on cpu-cpu: Error parsing message"

### ISSUE THREAD

**Issue by DimQ1** [microsoft/Olive#755]
### What happened?

I'm trying to convert the Whisper-medium model and as a result I get this error

![image](https://github.com/microsoft/Olive/assets/17319996/3de807f1-30de-4b32-95bb-d7324698e817)

### Version?

Olive-ai 0.4.0

**Comment by trajepl** [comment]
Seems like it failed to load the model back when load_external_data=False.

I tried it with latest main branch, it worked for me. Could you help use the latest changes from Olive and try it again:
```bash
pip install git+https://github.com/microsoft/Olive
python prepare_whisper_configs.py --model_name openai/whisper-medium
python -m olive.workflows.run --config whisper_cpu_fp32.json
```

**Comment by DimQ1** [comment]
I still get the error

`PS E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper> python prepare_whisper_configs.py --model_name openai/whisper-small --multilingual --no_audio_decoder
PS E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper> python -m olive.workflows.run --config whisper_cpu_int8.json --setup
[2023-11-28 22:49:29,678] [INFO] [run.py:136:dependency_setup] The following packages are required in the local environment: ['onnxruntime']
[2023-11-28 22:49:29,724] [INFO] [run.py:261:check_local_ort_installation] onnxruntime is already installed.
PS E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper> python -m olive.workflows.run --config whisper_cpu_int8.json
[2023-11-28 22:49:38,231] [DEBUG] [engine.py:125:setup_accelerators] Initial execution providers: ['CPUExecutionProvider']
[2023-11-28 22:49:38,231] [DEBUG] [engine.py:143:setup_accelerators] Initial accelerators: ['cpu']
[2023-11-28 22:49:38,231] [DEBUG] [engine.py:164:setup_accelerators] Supported execution providers for device cpu: ['CPUExecutionProvider']
[2023-11-28 22:49:38,232] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: cpu-cpu
[2023-11-28 22:49:38,292] [DEBUG] [engine.py:488:run_no_search] Running ['conversion', 'transformers_optimization', 'onnx_dynamic_quantization', 'insert_beam_search', 'prepost'] with no search ...
[2023-11-28 22:49:38,292] [INFO] [engine.py:931:_run_pass] Running pass conversion:OnnxConversion
[2023-11-28 22:49:38,293] [DEBUG] [resource_path.py:157:create_resource_path] Resource path code/user_script.py is inferred to be of type file.
[2023-11-28 22:49:38,295] [DEBUG] [resource_path.py:157:create_resource_path] Resource path code is inferred to be of type folder.
[2023-11-28 22:49:38,297] [DEBUG] [resource_path.py:157:create_resource_path] Resource path code is inferred to be of type folder.
[2023-11-28 22:49:38,298] [DEBUG] [resource_path.py:157:create_resource_path] Resource path code/user_script.py is inferred to be of type file.
[2023-11-28 22:49:38,314] [DEBUG] [resource_path.py:157:create_resource_path] Resource path E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper\code is inferred to be of type folder.
[2023-11-28 22:49:38,316] [DEBUG] [resource_path.py:157:create_resource_path] Resource path E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper\code\user_script.py is inferred to be of type file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\__main__.py", line 28, in <module>
    run(**var_args)
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\run.py", line 241, in run
    return run_engine(config, data_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\workflows\run\run.py", line 213, in run_engine
    return engine.run(
           ^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 349, in run
    run_result = self.run_accelerator(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 418, in run_accelerator
    return self.run_no_search(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 489, in run_no_search
    should_prune, signal, model_ids = self._run_passes(
                                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 894, in _run_passes
    model_config, model_id = self._run_pass(
                             ^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\engine\engine.py", line 992, in _run_pass
    output_model_config = host.run_pass(p, input_model_config, data_root, output_model_path, pass_search_point)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\systems\local.py", line 34, in run_pass
    output_model = the_pass.run(model, data_root, output_model_path, point)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\passes\olive_pass.py", line 371, in run
    output_model = self._run_for_config(model, data_root, config, output_model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\passes\onnx\conversion.py", line 97, in _run_for_config
    component_model = model.get_component(component_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\model\__init__.py", line 758, in get_component
    model_component = user_module_loader.call_object(hf_component.component_func, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\olive\common\user_module_loader.py", line 32, in call_object
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper\code\user_script.py", line 13, in get_encoder_decoder_init
    model = WhisperForConditionalGeneration.from_pretrained(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2600, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\hub.py", line 430, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\Dimq1\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '<olive.model.PyTorchModel object at 0x000001C7A495F5D0>'.
PS E:\Work\Dimq1\source\OpenAI\Olive\examples\whisper>`

**Comment by trajepl** [comment]
Weird, seems you were using the wrong model name of whisper which cannot be found in huggingface. Could you help double check if the model name is right under `whisper_cpu_int8.json`?
![image](https://github.com/microsoft/Olive/assets/13343117/1cecf53e-91e1-4b1c-9c77-e3e0d6ef930a)

**Comment by DimQ1** [comment]
Hey everything is correct in the configuration. And I still have not been able to convert large model using cpu-int8 configuration.
But It works fine for gpu-int8 what the difference there.
Also, if you convert using different configurations for the processor and video card with the same quantization level, you get models of different sizes and performance. Is this how it should be?

**Comment by DimQ1** [comment]
Hey. 
Videocard means - that I used "whisper_gpu_int8.json" as a configuration for converting model
processor - "whisper_cpu_int8.json"
quantization as I understand int8 in this configuration.

I suspect that I have no enough memory in my computer.
