### ISSUE TITLE
[Bug]: Converting Facebook MusicGen model to Onnx - RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#756]
### What happened?

Trying to convert facebook/musicgen-small model from HF.

**RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)**

Thanks,
Ash

Here is the code I used 
```
from olive.workflows import run as olive_run
import torch

def optimize_musicgen_model(config_path):
    # Run the Olive optimization workflow
    olive_run(config_path)

if __name__ == "__main__":

    from transformers import MusicgenForConditionalGeneration

    model = MusicgenForConditionalGeneration.from_pretrained("facebook/musicgen-small")
    model.eval()
    # Save the model's state dictionary in PyTorch format
    torch.save(model, "musicgen_model_full.pt")

    config_path = "config.json"
    optimize_musicgen_model(config_path)
```

**Config File**
```
{
    "input_model": {
        "type": "PyTorchModel",
        "config": {
            "model_path": "musicgen_model_full.pt",
            "io_config": {
                "input_names": ["input_ids", "attention_mask"],
                "input_shapes": [[1, 256], [1, 256]],
                "output_names": ["output"]
            }
        }
    },
    "evaluators": {
        "my_evaluator": {
            "metrics": [
                {
                    "name": "my_latency_metric",
                    "type": "latency",
                    "sub_types": [{"name": "avg"}]
                }
            ]
        }
    },
    "passes": {
        "onnx_conversion": {
            "type": "OnnxConversion",
            "config": {
                "target_opset": 13,
                "opt_level": 0,
                "float16": true,
                "use_gpu": true,
                "keep_io_types": false
            }
        },
        "quantization": {
            "type": "OnnxDynamicQuantization"
        }
    },
    "engine": {
        "log_severity_level": 0,
        "evaluator": "my_evaluator",
        "execution_providers": ["DmlExecutionProvider","CPUExecutionProvider"]
    }
}
```

**Error**
```
C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
[2023-11-26 14:56:56,909] [DEBUG] [engine.py:123:setup_accelerators] Initial execution providers: ['DmlExecutionProvider', 'CPUExecutionProvider']
[2023-11-26 14:56:56,909] [WARNING] [accelerator.py:122:infer_accelerators_from_execution_provider] Execution provider CPUExecutionProvider is mapped to multiple accelerators ['cpu', 'gpu']. Olive cannot infer the device which may cause unexpected behavior. Please specify the accelerator in the accelerator configs
[2023-11-26 14:56:56,909] [WARNING] [accelerator.py:122:infer_accelerators_from_execution_provider] Execution provider CPUExecutionProvider is mapped to multiple accelerators ['cpu', 'gpu', 'npu']. Olive cannot infer the device which may cause unexpected behavior. Please specify the accelerator in the accelerator configs
[2023-11-26 14:56:56,909] [WARNING] [engine.py:133:setup_accelerators] Cannot infer the accelerators from the target system. Use CPU as default.
[2023-11-26 14:56:56,909] [DEBUG] [engine.py:141:setup_accelerators] Initial accelerators: ['CPU']
[2023-11-26 14:56:56,909] [DEBUG] [engine.py:162:setup_accelerators] Supported execution providers for device cpu: ['CPUExecutionProvider']
[2023-11-26 14:56:56,909] [INFO] [engine.py:179:setup_accelerators] Running workflow on accelerator specs: cpu-cpu
[2023-11-26 14:56:56,909] [WARNING] [engine.py:183:setup_accelerators] The following execution provider is not supported: DmlExecutionProvider. Please consider installing an onnxruntime build that contains the relevant execution providers.
[2023-11-26 14:56:56,925] [WARNING] [config_utils.py:308:validate_config] Keys {'use_gpu', 'opt_level', 'keep_io_types', 'float16'} are not part of OnnxConversionConfig. Ignoring them.
[2023-11-26 14:56:56,925] [DEBUG] [engine.py:1069:_evaluate_model] Evaluating model ...
[2023-11-26 14:56:56,925] [DEBUG] [resource_path.py:157:create_resource_path] Resource path musicgen_model_full.pt is inferred to be of type file.
[2023-11-26 14:56:56,938] [DEBUG] [resource_path.py:157:create_resource_path] Resource path musicgen_model_full.pt is inferred to be of type file.
[2023-11-26 14:56:56,940] [DEBUG] [config.py:154:fill_in_params] Missing parameter data_dir for component load_dataset
[2023-11-26 14:56:58,040] [WARNING] [engine.py:436:run_accelerator] Failed to run Olive on cpu-cpu: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
Traceback (most recent call last):
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\olive\engine\engine.py", line 402, in run_accelerator
    results = self._evaluate_model(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\olive\engine\engine.py", line 1095, in _evaluate_model
    signal = self.target.evaluate_model(model_config, data_root, metrics, accelerator_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\olive\systems\local.py", line 47, in evaluate_model
    return evaluator.evaluate(model, data_root, metrics, device=device, execution_providers=execution_providers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 176, in evaluate
    metrics_res[metric.name] = self._evaluate_latency(
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 824, in _evaluate_latency
    session(**input_data) if input_is_dict else session(input_data)
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\transformers\models\musicgen\modeling_musicgen.py", line 1817, in forward
    encoder_outputs = self.text_encoder(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 1978, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 1016, in forward
    inputs_embeds = self.embed_tokens(input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "C:\Users\ashvi\miniconda3\Lib\site-packages\torch\nn\functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
```

### Version?

olive-ai                0.4.0
onnx                    1.15.0
onnxruntime             1.16.3
onnxruntime-directml    1.16.2
onnxruntime-gpu         1.16.3

**Comment by guotuofeng** [comment]
Not related to the issue. But only one onnxruntime should be installed. It seems you install three versions. 

Basically, you need remove all others before install any new ort. For example, if there is already onnxruntime-gpu installed and you'd like to install onnxruntime or onnxruntime-directml, Please manually uninstall onnxruntime-gpu before installing.

**Comment by AshD** [comment]
Thanks Mike. I rebuilt the venv and now have
olive-ai               0.5.0
omegaconf              2.3.0
onnx                   1.15.0
onnxruntime-directml   1.16.2
onnxruntime-extensions 0.9.0

**Comment by jambayk** [comment]
You are using the `io_config` of the input model to generate the dummy inputs but do not provide the data types for the inputs. 
So, Olive assumes that all inputs have `float` data type. Please provide the correct `input_types` like in this example https://github.com/microsoft/Olive/blob/3a74d46a752957e891c016623b25d6f45e254666/examples/bert/bert_inc_dynamic_ptq_cpu.json#L10

**Comment by AshD** [comment]
Thanks @jambayk 

This model is a little more complex than I thought and has three sub models

Here is a conversion using OpenVino
https://docs.openvino.ai/2023.2/notebooks/250-music-generation-with-output.html

Thanks,
Ash

**Comment by AshD** [comment]
Closing this issue for now since it needs more work in model definitions and it's not a bug!
