### ISSUE TITLE
[Bug]: Stable Diffusion conversion - TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#757]
### What happened?

Running python stable_diffusion.py --model_id="softwareweaver/HaveAll-Diffusers" --optimize
Error: **TypeError: 'NoneType' object is not callable**

Thanks,
Ash

Stack
```
Optimizing unet
[2023-11-27 07:40:31,042] [INFO] [engine.py:179:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-11-27 07:40:31,052] [INFO] [engine.py:929:_run_pass] Running pass convert:OnnxConversion
Traceback (most recent call last):
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 355, in <module>
    optimize(args.model_id, unoptimized_model_dir, optimized_model_dir)
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 221, in optimize
    olive_run(olive_config)
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\workflows\run\run.py", line 193, in run
    return engine.run(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\engine\engine.py", line 347, in run
    run_result = self.run_accelerator(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\engine\engine.py", line 425, in run_accelerator
    return self.run_search(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\engine\engine.py", line 589, in run_search
    should_prune, signal, model_ids = self._run_passes(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\engine\engine.py", line 892, in _run_passes
    model_config, model_id = self._run_pass(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\engine\engine.py", line 990, in _run_pass
    output_model_config = host.run_pass(p, input_model_config, data_root, output_model_path, pass_search_point)
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\systems\local.py", line 32, in run_pass
    output_model = the_pass.run(model, data_root, output_model_path, point)
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\passes\olive_pass.py", line 371, in run
    output_model = self._run_for_config(model, data_root, config, output_model_path)
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\passes\onnx\conversion.py", line 121, in _run_for_config
    return self._convert_model_on_device(model, data_root, config, output_model_path, device, torch_dtype)
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\passes\onnx\conversion.py", line 343, in _convert_model_on_device
    converted_onnx_model = OnnxConversion._export_pytorch_model(
  File "C:\AI\research\olive\.venv\lib\site-packages\olive\passes\onnx\conversion.py", line 216, in _export_pytorch_model
    torch.onnx.export(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\onnx\utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\onnx\utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\onnx\utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\onnx\utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\jit\_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\jit\_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\jit\_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 932, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\AI\research\olive\.venv\lib\site-packages\diffusers\models\embeddings.py", line 225, in forward
    sample = sample + self.cond_proj(condition)
TypeError: 'NoneType' object is not callable
```

### Version?

olive-ai 0.4.0
onnx 1.15.0
onnxruntime 1.16.3
onnxruntime-directml 1.16.2
onnxruntime-gpu 1.16.3

**Comment by AshD** [comment]
Re-installed everything and the problem went away :-)
