### ISSUE TITLE
[Bug]: local_resource_path.save_to_dir(save_dir, save_name, overwrite) failed

### ISSUE THREAD

**Issue by ningx-ms** [microsoft/Olive#777]
### What happened?

WSL2 + Ubuntu 20.04 as docker container. 

The adapter files are copied successfully and able to be loaded for inferencing. 
Maybe some file attributes failed to copy?

Note that in my setup, `workspace` and `project` is a folder on Windows file system, then mapped to a WSL Dev container.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/olive/engine/engine.py", line 412, in run_accelerator
    return self.run_no_search(
  File "/opt/conda/lib/python3.9/site-packages/olive/engine/engine.py", line 513, in run_no_search
    output_model_json = cache_utils.save_model(
  File "/opt/conda/lib/python3.9/site-packages/olive/cache.py", line 243, in save_model
    model_json["config"][resource_name] = local_resource_path.save_to_dir(save_dir, save_name, overwrite)
  File "/opt/conda/lib/python3.9/site-packages/olive/resource_path.py", line 223, in save_to_dir
    shutil.copytree(self.config.path, new_path)
  File "/opt/conda/lib/python3.9/shutil.py", line 569, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/conda/lib/python3.9/shutil.py", line 523, in _copytree
    raise Error(errors)
shutil.Error: [('/workspaces/project/cache/models/13_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-15f04465a66a0c973c4fcafcb8d646dd/output_model/adapter/adapter_config.json', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/adapter_config.json', '[Errno 1] Operation not permitted'), ('/workspaces/project/cache/models/13_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-15f04465a66a0c973c4fcafcb8d646dd/output_model/adapter/adapter_model.bin', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/adapter_model.bin', '[Errno 1] Operation not permitted'), ('/workspaces/project/cache/models/13_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-15f04465a66a0c973c4fcafcb8d646dd/output_model/adapter/README.md', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/README.md', '[Errno 1] Operation not permitted'), ('/workspaces/project/cache/models/13_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-15f04465a66a0c973c4fcafcb8d646dd/output_model/adapter', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter', '[Errno 1] Operation not permitted')]

### Version?

olive-ai==0.3.3

**Comment by xiaoyu-work** [comment]
Did you verify the output model inference is correct with adapter files? Even with this error, the adapter files copied and worked successfully (which means we shouldn't get this permission error).

**Comment by guotuofeng** [comment]
It seems like a Python shutil error. I googled website and find a couple of questions similar to this one. for example. https://bugs.python.org/issue36823

@jambayk, should we catch the exception and log one line error and let the Olive keep going?

**Comment by ningx-ms** [comment]
> Did you verify the output model inference is correct with adapter files? Even with this error, the adapter files copied and worked successfully (which means we shouldn't get this permission error).

Inference on the copied model is correct. 
I agree with @guotuofeng that it's better to catch this exception if not able to nail down the root cause, to ensure Olive finishes all steps.

**Comment by jambayk** [comment]
@ningx-ms thanks for raising the issue. Could you try the changed in this PR https://github.com/microsoft/Olive/pull/779 to see if it works as expected in your case. 

You can turn on debug logging by adding `"log_severity_level" : 0` under `"engine"` section in the workflow config json.

**Comment by ningx-ms** [comment]
Is there a wheel for me to test that or could you just complete the PR? 
I am running Olive in a dev container, hard to install the package from source.

**Comment by jambayk** [comment]
I am waiting for approval to merge the PR and was originally hoping you could test it before that too. 

I don't have a wheel for it but can build and share one offline if needed. 
BTW, it is also possible to install from my dev branch directly using pip:
```
pip install git+https://github.com/microsoft/Olive@jambayk/copytree
```
It works like any other requirement such as `olive-ai`

**Comment by ningx-ms** [comment]
I could confirm that the fix in your branch catches the exception and allows Olive to run through the rest steps.
The adapter can be loaded without issue.

Thanks for the quick fix!



[2023-12-05 22:41:05,217] [DEBUG] [engine.py:911:_run_passes] Signal: None
[2023-12-05 22:41:05,235] [DEBUG] [resource_path.py:157:create_resource_path] Resource path /workspaces/project/cache/models/1_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-a02b4fe7610210e13547c46565e68634/output_model/adapter is inferred to be of type folder.
[2023-12-05 22:41:10,377] [WARNING] [utils.py:304:copy_dir] Received shutil.Error '[('/workspaces/project/cache/models/1_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-a02b4fe7610210e13547c46565e68634/output_model/adapter/adapter_config.json', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/adapter_config.json', '[Errno 1] Operation not permitted'), ('/workspaces/project/cache/models/1_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-a02b4fe7610210e13547c46565e68634/output_model/adapter/adapter_model.bin', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/adapter_model.bin', '[Errno 1] Operation not permitted'), ('/workspaces/project/cache/models/1_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-a02b4fe7610210e13547c46565e68634/output_model/adapter/README.md', '/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter/README.md', '[Errno 1] Operation not permitted'), (PosixPath('/workspaces/project/cache/models/1_QLoRA-c2ac57d9dcdd152c5f5dbe6b31fb29ca-a02b4fe7610210e13547c46565e68634/output_model/adapter'), PosixPath('/workspaces/project/models/qlora/qlora/gpu-cpu_model/adapter'), '[Errno 1] Operation not permitted')]' but all required file names exist in destination directory. Assuming all files were copied successfully and continuing.
[2023-12-05 22:41:10,381] [INFO] [engine.py:359:run] Run history for gpu-cpu:
[2023-12-05 22:41:10,390] [INFO] [engine.py:636:dump_run_history] run history:

**Comment by jambayk** [comment]
PR with fix has been merged.
