### ISSUE TITLE
Can't reproduce optimization "Optimize_ONNX_Models_Latency_with_OLive.ipynb"

### ISSUE THREAD

**Issue by bulatnv** [microsoft/OLive#82]
```
C:\Users\user\PycharmProjects\olive\venv\Scripts\python.exe C:/Users/user/PycharmProjects/olive/main.py
2022-03-29 12:19:23,240 - olive.optimization_config - INFO - Checking the model file...
2022-03-29 12:19:23,294 - olive.optimization_config - INFO - Providers will be tested for optimization: ['CPUExecutionProvider', 'DnnlExecutionProvider']
2022-03-29 12:19:28,608 - olive.optimization_config - INFO - Checking the model file...
2022-03-29 12:19:28,663 - olive.optimization_config - INFO - Providers will be tested for optimization: ['CPUExecutionProvider', 'DnnlExecutionProvider']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\PycharmProjects\olive\main.py", line 24, in <module>
    result = optimize(opt_config)
  File "C:\Users\user\PycharmProjects\olive\venv\lib\site-packages\olive\optimize.py", line 24, in optimize
    pretuning_inference_result = get_benchmark(optimization_config)
  File "C:\Users\user\PycharmProjects\olive\venv\lib\site-packages\olive\optimization\tuning_process.py", line 189, in get_benchmark
    manager = Manager()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by leqiao-1** [comment]
Thanks for reporting this issue. 
To run olive optimization in a python script, you can put this sample script in ```test.py``` and run directly with ```python test.py```
olive code needs to be inside a function due to some multiprocessing settings.
```
from olive.optimization_config import OptimizationConfig
from olive.optimize import optimize

def model_optimize():
    opt_config = OptimizationConfig(model_path = "inception_v2.onnx")
    result = optimize(opt_config)

if __name__ == "__main__":
    model_optimize()
````

**Comment by bulatnv** [comment]
Hello @leqiao-1. 

Thank you for quick reply. I will try.
I was successful to run optimization with Command Line Tool.

Thank you kindly.
All the best.
