### ISSUE TITLE
Unable to convert openai/whisper-large-v3

### ISSUE THREAD

**Issue by DimQ1** [microsoft/Olive#823]
**Describe the bug**
Following the instructions from the conversion example Whisper. I've tried convert whisper-large-v3 model and process stuck.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
It would be great to have converted model :)

**Olive config**
[whisper_gpu_int8.json](https://github.com/microsoft/Olive/files/13685558/whisper_gpu_int8.json)

**Olive logs**
[2023-12-15 16:30:09,287] [DEBUG] [olive_evaluator.py:244:generate_metric_user_config_with_model_io] Model input shapes are not static. Cannot use inferred input shapes for creating dummy data. This will cause an error when creating dummy data for tuning.
[2023-12-15 16:30:09,291] [DEBUG] [resource_path.py:156:create_resource_path] Resource path D:\Learnig\AI\Olive\examples\whisper\data is inferred to be of type folder.
2023-12-15 16:30:33.6573681 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/whisper_encoder/encoder/conv1/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 80 kernel channels: 128 group: 1
2023-12-15 16:30:33.6656679 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_node' Status Message: Non-zero status code returned while running Conv node. Name:'/whisper_encoder/encoder/conv1/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 80 kernel channels: 128 group: 1
[2023-12-15 16:30:33,677] [WARNING] [engine.py:438:run_accelerator] Failed to run Olive on gpu-cuda: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_node' Status Message: Non-zero status code returned while running Conv node. Name:'/whisper_encoder/encoder/conv1/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 80 kernel channels: 128 group: 1
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\olive\engine\engine.py", line 418, in run_accelerator
    return self.run_no_search(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\engine\engine.py", line 489, in run_no_search
    should_prune, signal, model_ids = self._run_passes(
                                      ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\engine\engine.py", line 910, in _run_passes
    signal = self._evaluate_model(model_config, model_id, data_root, evaluator_config, accelerator_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\engine\engine.py", line 1097, in _evaluate_model
    signal = self.target.evaluate_model(model_config, data_root, metrics, accelerator_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\systems\local.py", line 49, in evaluate_model
    return evaluator.evaluate(model, data_root, metrics, device=device, execution_providers=execution_providers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 215, in evaluate
    metrics_res[metric.name] = self._evaluate_latency(
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 132, in _evaluate_latency
    latencies = self._evaluate_raw_latency(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 784, in _evaluate_raw_latency
    return self._evaluate_onnx_latency(model, metric, dataloader, post_func, device, execution_providers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\olive\evaluator\olive_evaluator.py", line 559, in _evaluate_onnx_latency
    session.run(input_feed=input_dict, output_names=None)
  File "C:\Program Files\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_node' Status Message: Non-zero status code returned while running Conv node. Name:'/whisper_encoder/encoder/conv1/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 80 kernel channels: 128 group: 1
[2023-12-15 16:30:33,824] [INFO] [engine.py:359:run] Run history for gpu-cuda:
[2023-12-15 16:30:33,849] [INFO] [engine.py:636:dump_run_history] run history:
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
| model_id                                                                           | parent_model_id
                                                   | from_pass                  |   duration_sec | metrics   |
+====================================================================================+====================================================================================+============================+================+===========+
| 21af6fd63fb2cee4d284801decbe1b9c                                                   |
                                                   |                            |                |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
| 0_OnnxConversion-21af6fd63fb2cee4d284801decbe1b9c-0f2f01796d1fdfcd7c7058df3febec4e | 21af6fd63fb2cee4d284801decbe1b9c                                                   | OnnxConversion             |      561.056   |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
| 1_OnnxMatMul4Quantizer-0-5acf130ba6aab2b20088ef9c38232bc6                          | 0_OnnxConversion-21af6fd63fb2cee4d284801decbe1b9c-0f2f01796d1fdfcd7c7058df3febec4e | OnnxMatMul4Quantizer       |       38.4159  |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
| 2_InsertBeamSearch-1-51b19e895c1591ef53a44fb74c8eac16                              | 1_OnnxMatMul4Quantizer-0-5acf130ba6aab2b20088ef9c38232bc6                          | InsertBeamSearch           |       28.3199  |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
| 3_AppendPrePostProcessingOps-2-4484c1c0cae499568680b10646e5cb27                    | 2_InsertBeamSearch-1-51b19e895c1591ef53a44fb74c8eac16                              | AppendPrePostProcessingOps |        9.64609 |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+----------------------------+----------------+-----------+
[2023-12-15 16:30:33,852] [INFO] [engine.py:374:run] No packaging config provided, skip packaging artifacts
PS D:\Learnig\AI\Olive\examples\whisper>

**Other information**
 - OS:  Windows
 - Olive version:  0.5.0
 - ONNXRuntime version: 16.

**Comment by jambayk** [comment]
Hi @DimQ1,

Thanks for bringing this up. I have already opened a PR to fix this. In the meanwhile, please try this branch https://github.com/microsoft/Olive/tree/jambayk/whisper-v3.

**Comment by DimQ1** [comment]
Hi your fixes work great. I've successfully converted whisper-large-v3.
But this model has a little different tokens that can be a reason some issues
![image](https://github.com/microsoft/Olive/assets/17319996/7c804bb9-b53f-4d8d-adb1-86b03ce3af63)

**Comment by DimQ1** [comment]
fixed by [PR](https://github.com/microsoft/Olive/pull/825)
