### ISSUE TITLE
Any workarounds to convert phi-2 model on Windows

### ISSUE THREAD

**Issue by gopitk** [microsoft/Olive#966]
**Describe the bug**
Trying to convert phi-2 to run on CPU. Tried both cpu_fp32 and cpu_int4

**To Reproduce**
Followed instructions and ran the command:
```python phi2.py --model_type cpu_int4```

**Expected behavior**
Compilation to work fine. Is there a workaround to compile the model in Windows? (besides potentially trying in WSL)

**Olive config**
Same as the one in the Olive/examples/phi2

**Olive logs**
_**RuntimeError: Windows not yet supported for torch.compile**_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\code\Olive\olive\engine\engine.py", line 345, in run_accelerator
    output_footprint = self.run_no_search(
  File "C:\code\Olive\olive\engine\engine.py", line 429, in run_no_search
    should_prune, signal, model_ids = self._run_passes(
  File "C:\code\Olive\olive\engine\engine.py", line 822, in _run_passes
    model_config, model_id = self._run_pass(
  File "C:\code\Olive\olive\engine\engine.py", line 933, in _run_pass
    output_model_config = host.run_pass(p, input_model_config, data_root, output_model_path, pass_search_point)
  File "C:\code\Olive\olive\systems\local.py", line 34, in run_pass
    output_model = the_pass.run(model, data_root, output_model_path, point)
  File "C:\code\Olive\olive\passes\olive_pass.py", line 377, in run
    output_model = self._run_for_config(model, data_root, config, output_model_path)
  File "C:\code\Olive\olive\passes\onnx\conversion.py", line 122, in _run_for_config
    return self._convert_model_on_device(model, data_root, config, output_model_path, device, torch_dtype)
  File "C:\code\Olive\olive\passes\onnx\conversion.py", line 399, in _convert_model_on_device
    converted_onnx_model = OnnxConversion._export_pytorch_model(
  File "C:\Users\gokuma\Miniconda3\envs\olivecpu\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\code\Olive\olive\passes\onnx\conversion.py", line 237, in _export_pytorch_model
    dynamo_export(
  File "C:\Users\gokuma\Miniconda3\envs\olivecpu\lib\site-packages\torch\onnx\_internal\exporter.py", line 1444, in dynamo_export

**Other information**
 - OS: Windows
 - Olive version: main branch 
 - ONNXRuntime package and version: 1.17.1 (cpu)

**Comment by trajepl** [comment]
![image](https://github.com/microsoft/Olive/assets/13343117/563167c8-77f3-42d9-b129-e485fb3b0f6a)
Try to disable `use_dynamo_exporter`

**Comment by guotuofeng** [comment]
From the time being, the dynamo export only works in Linux for opset 18 or later since the underlying torch doesn't support it.

**Comment by trajepl** [comment]
https://github.com/microsoft/Olive/pull/970
Try this.
